Unidata/tds

- build.gradle
- gradle/any/dependencies.gradle
These changes are in preparation for the netcdf-java build on travis-ci
to test PRs against the TDS master branch. To do so, we need to tell the
TDS build to look in the local maven repository for snapshots. Normally,
this is not something you'd want to do unless you were testing
netcdf-java changes against the TDS locally, therefore these are
commended out. The netcdf-java travis script will use sed to take care of
uncommenting the two entries.
> Prep to use local maven repository

- tds/src/main/java/thredds/server/ncss/controller/NcssGridController.java
- tds/src/main/java/thredds/server/wcs/v1_0_0_1/WcsCoverage.java
CFGridCoverageWriter2.writeOrTestSize is now split into two different
methods:
CFGridCoverageWriter2.write
CFGridCoverageWriter2.getSizeOfOutput
> Use new CFGridCoverageWriter2 write API

- gradle/any/dependencies.gradle
- it/src/test/java/thredds/server/catalog/TestTdsFCcatalogs.java
- it/src/test/java/thredds/server/ncss/TestGridAsPointP.java
- it/src/test/java/thredds/server/opendap/TestTdsDodsServer.java
- it/src/test/java/thredds/server/services/ConsistentDatesTest.java
- it/src/test/java/thredds/server/services/TestAdminDebug.java
- it/src/test/java/thredds/server/services/TestMetadataService.java
- it/src/test/java/thredds/server/wcs/TestWcsServer.java
- it/src/test/java/thredds/server/wms/TestWmsServer.java
- opendap/dtswar/src/main/java/opendap/dts/DTSServlet.java
- tds/src/main/java/thredds/server/ncss/view/dsg/point/PointSubsetWriterCSV.java
- tds/src/main/java/thredds/server/ncss/view/dsg/station/StationSubsetWriterCSV.java
- tds/src/main/java/thredds/server/opendap/NcSDString.java
- tds/src/main/java/thredds/server/opendap/OpendapServlet.java
- tds/src/main/java/thredds/server/radarServer2/RadarServerController.java
- tds/src/main/java/thredds/servlet/ServletUtil.java
- tds/src/test/java/thredds/server/ncss/view/dsg/DsgSubsetWriterTest.java
- tds/src/test/resources/thredds/server/ncss/view/dsg/station/waterml2/outputAll.xml
- tds/src/test/resources/thredds/server/ncss/view/dsg/station/waterml2/outputSubset1.xml
- tds/src/test/resources/thredds/server/ncss/view/dsg/station/waterml2/outputSubset2.xml
* Make sure we use the same JNA version as netcdf-java (was causing a chronicle-map error on windows)
* use `java.nio.charset.StandardCharsets.UTF_8` instead of `opendap.dap.Util.UTF8`, `ucar.nc2.constants.CDM`
* Use `ucar.nc2.time.CalendarDate` over joda time
> Various updates to bring in line with latest netcdf-java

- dap4/d4tests/build.gradle
- gradle/any/dependencies.gradle
- it/build.gradle
- it/src/test/java/ucar/nc2/util/net/TestMisc.java
- opendap/dtswar/build.gradle
- opendap/server/build.gradle
- tdcommon/build.gradle
- tdm/build.gradle
- tds/build.gradle
- testUtil/build.gradle
Use the new modules introduced in netcdf-java 5.2 (currently snapshot) (brings TDS up-to-date with Unidata/netcdf-java#124).
> Use new netcdf-java modules.

- it/src/test/java/thredds/server/opendap/TestTdsDodsServer.java
- tds/src/main/java/thredds/server/opendap/OpendapServlet.java
Was working for ascii request, this makes it work properly using `TdsErrorHandling` for dods requests. 
An overly happy `catch Exception` made this interesting.
> Make sure RequestTooLarge message returned for .dods

- gradle/any/testing.gradle
- gradle/root/testing.gradle
For now, ignore dap4 tests when running the tds check from the
netCDF-Java GitHub Action.
> Ignore dap4 tests when running from netcdf-java ci

- gradle/any/dependencies.gradle
- it/src/test/java/thredds/server/wms/TestWmsServer.java
- tds/src/main/java/thredds/server/wms/ThreddsWmsCatalogue.java
- tds/src/main/webapp/WEB-INF/applicationContext.xml
- tds/src/main/webapp/WEB-INF/web.xml
Update TDS WMS configuration so that TDS request filters don't block `GetLegendGraphic` requests that use the `SLD` or `SLD_BODY` parameters. Switch filter used in Spring config to allow angle brackets ('<' and '>') in query string and remove duplicate filter from `web.xml`. 
(This PR also updates the edal-wms dependency to 1.4.2, from SNAPSHOT.)
> Update TDS WMS configuration to support SLD parameter

- gradle/any/dependencies.gradle
- tds/src/main/webapp/WEB-INF/web.xml
Because we are using `ContextLoaderListener` to bootstrap spring, we need to make sure the `Log4jServletContextListener` is called first or else we will get thread leaks on shutdown. See [this comment on LOG4J2-1259](https://issues.apache.org/jira/browse/LOG4J2-1259?focusedCommentId=15895026&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-15895026).
> Bump log4j2 deps and fix log4J listener loading

- .github/workflows/docs.yml
- .github/workflows/tds.yml
- it/src/test/java/thredds/server/cdmr/TestCdmRemoteCompareHeadersP.java
- it/src/test/java/thredds/server/ncss/NcssGridIntegrationTest.java
- it/src/test/java/thredds/server/ncss/TestGridAsPointP.java
- it/src/test/java/thredds/server/services/ConsistentDatesTest.java
- it/src/test/java/thredds/server/wcs/TestWcsServer.java
- tdcommon/src/main/java/thredds/server/catalog/DataRoot.java
- tds/src/main/java/thredds/core/DatasetManager.java
- tds/src/main/java/thredds/core/TdsRequestedDataset.java
- tds/src/main/java/thredds/featurecollection/InvDatasetFeatureCollection.java
- tds/src/main/java/thredds/server/admin/DebugCommands.java
- tds/src/main/java/thredds/server/config/TdsInit.java
- tds/src/main/java/thredds/server/reify/DownloadController.java
- tds/src/main/java/thredds/server/wfs/WFSController.java
- tds/src/main/java/thredds/server/wms/ThreddsWmsServlet.java
- tds/src/test/content/thredds/catalog.xml
- tds/src/test/content/thredds/tds-s3.xml
- tds/src/test/java/thredds/server/ncss/controller/grid/AllVariablesSubsettingTest.java
- tds/src/test/java/thredds/server/ncss/controller/grid/FmrcHorizSubsettingTest.java
- tds/src/test/java/thredds/server/ncss/controller/grid/SpatialSubsettingTest.java
- tds/src/test/java/thredds/server/ncss/controller/grid/TemporalSpaceSubsettingTest.java
- tds/src/test/java/thredds/server/ncss/controller/grid/VariableSpaceSubsettingTest.java
- tds/src/test/java/thredds/server/ncss/controller/grid/VerticalStrideSubsettingTest.java
- tds/src/test/java/thredds/server/ncss/view/dsg/DsgSubsetWriterTest.java
- tds/src/test/java/thredds/server/opendap/TestCEEvaluator.java
- testUtil/src/main/java/ucar/unidata/util/test/TestDir.java
- testUtil/src/main/java/ucar/unidata/util/test/UnitTestCommon.java
This PR enables the TDS and its tests to configure whether or not the
new netCDF-Java API is used when reading data (that is, whether or not
it will use the new NetcdfFiles and NetcdfDatasets methods). If the
dataset being served by the TDS is on an object store, it will be
accessed via the new API, as that is the only choice.
> Allow TDS to use both old and new netCDF-Java API

- gradle/any/dependencies.gradle
Use a special set of edal-java artifacts which were recompiled against
5.4.0-SNAPSHOT and published on our nexus server. See
https://github.com/lesserwhirls/edal-java/tree/edal-1.4.2.1-unidata
Fixes Unidata/netcdf-java#313
> Use special edal build

- gradle/any/dependencies.gradle
- tds/build.gradle
- tds/src/test/content/thredds/pointCatalog.xml
- tds/src/test/java/thredds/server/ncss/controller/point/TestStationFcOpenFiles.java
Add a test to the TDS to make sure the bug in Unidata/netcdf-java#320
is fixed when CompositeStationCollection is used by a featureCollection
featureType=Station collection (see Unidata/tds#88)
> featureCollection featureType Station file handles

- gradle/any/shared-mvn-coords.gradle
- tds-platform/build.gradle
- tds/build.gradle
- tds/src/main/webapp/WEB-INF/web.xml
Needed to exclude some logging backends from the TDS war. Oops. Also, moved the hibernate validator related dependencies to use the annotation processor for hibernate validator.
> Fix logging and use hibernate-validator-annotation-processor

- tds/src/main/java/thredds/servlet/filter/HttpHeadFilter.java
- tds/src/main/webapp/WEB-INF/applicationContext.xml
Requests for large files (larger than 2GB) via the fileServer service
were getting an invalid content length assigned due to the
HttpHeadFilter using int instead of long. The fileServer controller sets
the correct content-length value, which gets overwritten by the filter.
This PR does two things:
1) Configure fileServer to bypass HttpHeadFilter (which fixes Unidata/tds#52)
2) Fix HttpHeadFilter to track response size using long instead of int.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/112)
> Fix HttpHeadFilter for large requests

- docs/src/public/userguide/pages/tds_tutorial/tds_configuration/CustomizingTdsLookAndFeel.md
- tds/src/main/java/thredds/server/TdsErrorHandling.java
- tds/src/main/java/thredds/server/catalogservice/CatalogViewContextParser.java
- tds/src/main/java/thredds/server/exception/MethodNotImplementedException.java
- tds/src/main/java/thredds/server/notebook/JupyterNotebookServiceCache.java
- tds/src/main/java/thredds/server/notebook/JupyterNotebookViewerService.java
- tds/src/main/java/thredds/server/notebook/NotebookController.java
- tds/src/main/java/thredds/server/notebook/NotebookMetadata.java
- tds/src/main/java/thredds/server/viewer/ViewerLinkProvider.java
- tds/src/main/java/thredds/server/viewer/ViewerService.java
- tds/src/main/java/thredds/server/viewer/ViewerServiceImpl.java
- tds/src/main/java/thredds/server/wms/Godiva3Viewer.java
- tds/src/main/webapp/WEB-INF/altContent/startup/jupyter_notebooks/default_viewer.ipynb
- tds/src/main/webapp/WEB-INF/templates/datasetFragments.html
- Update notebook service to have 2 endpoint: get a list all notebooks for a given dataset, and get a specific notebook
- Update dataset HTML page to show all available notebooks
- Change JupyterNotebook access type to new "DataViewer" access and remove from Access tab (only in Viewers tab)
- Change JupyterNotebookViewer logic:
- Each notebook has its own JupyterNotebookViewer
- New JupyterNotebookViewerService registers a list of all JupyterNotebookViewers
- added a, optional description and a type to Viewer objects
TODO:
- include screenshots in docs
- add tests for notebook service
Depends on [netcdf-java#507](https://github.com/Unidata/netcdf-java/pull/507)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Enable multiple notebooks in notebook service; update notebook docs

- .github/workflows/tds.yml
- build.gradle
- buildSrc/build.gradle
- docs/build.gradle
- gradle/any/dependencies.gradle
- gradle/any/gretty.gradle
- gradle/any/java-internal.gradle
- gradle/any/shared-mvn-coords.gradle
- gradle/root/coverage.gradle
- gradle/root/sonarqube.gradle
- gradle/wrapper/gradle-wrapper.properties
- project-files/owasp-dependency-check/dependency-check-suppression.xml
- tds-platform/build.gradle
- tds-testing-platform/build.gradle
- tds/build.gradle
- testUtil/build.gradle
* Bump the following Bill of Materials versions:
* netndf-java-bom (5.4.0-SNAPSHOT to 5.2.0-SNAPSHOT)
* spring-framework-bom (5.3.1 to 5.3.4)
* spring-security-bom (5.4.1 to 5.4.5)
* chronicle-bom (2.20.93 to 2.21ea74)
* Utilize the netcdf-java-testing-platform for testing dependency
management
* Suppress OWAPS dependency check false positives
* Move to edal-java 1.5.0
* this forces the minimum required version of Java from 8 to 11.
* Upgrade to Gradle 6.8.3
* Migrate away from `jcenter`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/123)
> Dependency and Gradle Upgrades

- tdcommon/src/main/java/thredds/server/catalog/tracker/DatasetExt.java
- tdcommon/src/main/java/thredds/server/catalog/tracker/DatasetExtBytesMarshaller.java
- tdcommon/src/main/java/thredds/server/catalog/tracker/DatasetTrackerChronicle.java
- tds-platform/build.gradle
- tds/build.gradle
- tds/src/main/java/thredds/server/config/TdsInit.java
- tds/src/main/webapp/WEB-INF/spring-servlet.xml
- tds/src/main/webapp/WEB-INF/web.xml
- tds/src/test/java/thredds/server/catalog/tracker/TestChronicleTracker.java
* Use unidata snapshot of `edal-java`, which is compiled against `5.4.2` (base dependency is compiled against `5.3.3`).
* Use chronicle-map [custom serializers](https://github.com/OpenHFT/Chronicle-Map/blob/ea/docs/CM_Tutorial.adoc#custom-serializers) for persisting instead of relying on `Externalizable`.
* Make sure the new builder-based Aggregation code is configured to use a DiskCache and uses the same proto dataset as the now deprecated Aggregation code.
* Squash a few startup warning messages related to Thymeleaf (template mode) deprecation.
* Make only one slf4j binding makes it on the classpath, otherwise we lose control of logging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Various Fixes

- tds/src/main/java/thredds/featurecollection/cache/GridInventoryCacheChronicle.java
- tds/src/main/java/thredds/server/config/TdsInit.java
- tds/src/main/resources/META-INF/services/ucar.nc2.internal.dataset.ft.fmrc.InventoryCacheProvider
- tds/src/main/webapp/WEB-INF/classes/log4j2.xml
Implement a InventoryCacheProvider using ChronicleMap to enable a
persistent cache for FMRC GridDatasetInv caching.
Resolves Unidata/tds#19.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/135)
> Implement persistent caching for FMRC GridDatasetInv

- tds/src/main/java/thredds/core/DatasetManager.java
- tds/src/main/java/thredds/featurecollection/InvDatasetFcFmrc.java
- tds/src/main/java/thredds/featurecollection/InvDatasetFeatureCollection.java
- tds/src/main/java/thredds/server/config/TdsInit.java
No longer allow the use of the old API at runtime as a `threddsConfig.xml` option or Java systems property. Also, fix a few modifier order issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/140)
> Use new netCDF-java API

- tds/src/main/java/thredds/server/config/TdsUpdateConfigBean.java
- tds/src/main/java/thredds/server/opendap/OpendapServlet.java
- tds/src/main/java/thredds/server/wcs/WCSController.java
Make sure the OPeNDAP and WCS init sequence happens after threddsConfig.xml has been read. This issue was introduce after migrating to a new version of spring and was just now noticed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/154)
> Fix service init sequence

- tds/src/main/webapp/js/ncss/ncssApp.js
The NetCDF Subset Service pages show a map with an OpenStreetMap layer, but there is no attribution to credit OpenStreetMap :
https://www.openstreetmap.org/copyright/en
The map with OpenStreetMap credit : 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/159)
> Fix missing OpenStreetMap attribution for NCSS maps

- gradle/any/shared-mvn-coords.gradle
- tds-platform/build.gradle
- tds-testing-platform/build.gradle
Use the log4j bom with enforcedPlatform in tds-platform project to allow us to define the log4j version in one spot while controlling transitive version resolution at the same time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/183)
> Upgrade to log4j 2.17.0

- tds/build.gradle
To prevent the %23%23 encoding for nexus
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/201)
> removed hash chars from war file

- tds-test-utils/src/main/java/thredds/test/util/TestOnLocalServer.java
- tds/src/integrationTests/java/thredds/server/fileserver/TestFileServer.java
- tds/src/integrationTests/java/thredds/server/fileserver/TestPartialContent.java
- tds/src/main/java/thredds/server/fileserver/FileServerController.java
- tds/src/main/java/thredds/servlet/ServletUtil.java
- For fileserver, use `MFile:writeToStream` to write both files and s3 objects to response (see [netcd-java PR](https://github.com/Unidata/netcdf-java/pull/988))
- Refactoring of `ServletUtil:returnFile` to pull out common code for use in `writeMFileToResponse` function
- Unignore s3 fileserver test
- Update fileserver tests to check md5 of file downloaded
- Add tests for partial content and head
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/208)
> [5.x] Udt 134933 s3 fileserver problems

- tdcommon/src/main/java/thredds/server/catalog/ConfigCatalogCache.java
- tdcommon/src/main/java/thredds/server/catalog/builder/ConfigCatalogBuilder.java
- tds/src/main/java/thredds/server/config/TdsInit.java
- tds/src/test/java/thredds/server/catalog/TestConfigCatalogBuilder.java
- tds/src/test/java/thredds/server/catalog/TestUseRemoteReference.java
- tds/src/test/java/thredds/server/catalogservice/TestContext.java
- Remove hardcoded "thredds" context from ConfigCatalogBuilder that was being used when creating DatasetScans and FeatureCollections
- Add some tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/211)
> [5.x] Fix context problem

- tds-testing-platform/build.gradle
See [CVE-2022-22950](https://nvd.nist.gov/vuln/detail/CVE-2022-22950)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/216)
> upgrade spring-test in test platform

- tds/src/main/java/thredds/server/catalogservice/RemoteCatalogServiceController.java
- tds/src/test/java/thredds/server/catalogservice/RemoteCatalogControllerTest.java
- Add the parameter "htmlView" to remoteCatalogService command=show requests so that it is possible to get a whole catalog as xml (previously only allowed with command=subset)
- Extend tests to test this parameter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/228)
> [5.x] Remote catalog as xml

- docs/devguide/src/site/pages/thredds/ThreddsConfigRef.md
- tds/src/main/java/thredds/featurecollection/cache/GridInventoryCacheChronicle.java
- tds/src/main/java/thredds/server/config/TdsInit.java
- tds/src/test/content/thredds/threddsConfig.xml
- tds/src/test/java/thredds/server/config/ThreddsConfigTest.java
Address #196 and #230:
- Make FeatureCollection cache `maxEntries` and `maxBloatFactor` parameters configurable through threddsConfig
- Update threddsConfig docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/232)
> make featurecollection cache configurable through threddsConfig

- gradle/any/dependencies.gradle
- settings.gradle
- tds-ui/README.md
- tds-ui/build.gradle
This PR adds a subproject called `tds-ui`, which is a version of ToolsUI that corresponds to the version of netCDF-Java in use by the TDS, plus extras that are not included with toolsUI, like the `cdm-s3` subproject from netCDF-Java. This exists simply for developer convenience and is not published anywhere. To run toolsUI from the TDS project, execute the following gradle command from the top of the repository:
~~~shell
./gradlew :tds-ui:run
~~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/234)
> Add subproject for TDS toolsUI

- tds/src/main/java/thredds/core/DatasetManager.java
- tds/src/main/java/thredds/core/TdsRequestedDataset.java
- tds/src/main/java/thredds/servlet/ServletUtil.java
- tds/src/test/content/thredds/catalog.xml
- tds/src/test/java/thredds/server/fileserver/FileServerControllerTest.java
- tds/src/test/java/thredds/server/ncss/controller/grid/GridDatasetControllerTest.java
Depends on [NetCDF-java PR](https://github.com/Unidata/netcdf-java/pull/1044). Issue reported in https://github.com/Unidata/tds/issues/235
- Add tests
- Fix order of lookup for NCSS-- should first check for an ncml `location` attribute, then look at datasetRoot in the `urlPath` (which may not point to a file in the case of a ncml `location`, which previously resulted in a FileNotFound exception).
- Improve error message
- Fix FileServer dataset lookup for a ncml `location` attribute.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/240)
> [5.x] Ncss dataset root with location bug

- tds-test-utils/src/main/java/thredds/test/util/TestOnLocalServer.java
Together with the [netcdf-java PR](https://github.com/Unidata/netcdf-java/pull/1046), this change would fix the tests that were failing in TestAdminDebug by allowing self-signed certificates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/244)
> [5.x] Allow self-signed certificates to fix failing tests

- tds/src/main/java/thredds/server/opendap/OpendapServlet.java
The `baseURI` member gets set and logged but never used otherwise.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/246)
> [5.x] Remove unused code

- tds/src/main/java/thredds/core/DatasetManager.java
- tds/src/main/java/thredds/server/TdsErrorHandling.java
- tds/src/main/java/thredds/server/catalogservice/CatalogViewContextParser.java
- tds/src/test/java/thredds/server/ncss/controller/point/TestPointFCExceptions.java
- Improve /ncss/point error handling when dataset cannot be opened as a point dataset. Previously, nothing was logged and status was OK. Now the status returned is "method not allowed" and the error log is printed. I also added a test for this.
- Now the description shown in the browser for /ncss/grid or /ncss/point contains the word "grid" or "point" so that you can differentiate them if both are configured. It is a bit of a hacky fix, but they both correspond to the same ServiceType enum in Netcdf-java, and I thought it might not be a good to change that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/251)
> [5.x] Improve ncss error handling and service description

- tds/src/integrationTests/java/thredds/server/ncss/NcssGridIntegrationTest.java
- tds/src/test/java/thredds/server/ncss/controller/grid/GridDatasetControllerTest.java
- tds/src/test/java/thredds/server/ncss/controller/grid/SpatialSubsettingTest.java
- tds/src/test/java/thredds/server/ncss/controller/grid/TemporalSpaceSubsettingTest.java
- tds/src/test/java/thredds/server/ncss/controller/grid/VariableSpaceSubsettingTest.java
- tds/src/test/java/thredds/server/ncss/controller/point/TestStationFCController.java
If you don't have the netcdf4 library installed and the right environment variable set pointing to it, then some tests will fail (other than the ones on Jenkins that fail). This change would ignore those tests if the library isn't found, otherwise run them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/252)
> Ignore tests that require netcdf4 library if this cannot be found

- tds/src/main/java/thredds/server/admin/AdminCollectionController.java
- Add "test" as well as "nocheck" trigger link to admin page
- Fix collection links on the “Show all collection status” page (`admin/collection/showStatus`). Previously this gave a 404 error. Now this leads to `admin/collection/showCollection?collection=name` which calls `showStatus` for a feature collection.  I am not actually sure if this useful as you could get to that page from the "Show collections" (`admin/debug?Collections/showCollection`) page already, but as far as I can tell this is what happened in TDS 4.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/267)
> Fix admin show collection and add test trigger

- docs/adminguide/src/site/pages/thredds/GribConfigRef.md
- docs/devguide/src/site/pages/thredds/GribConfigRef.md
- docs/quickstart/src/site/pages/thredds/GribConfigRef.md
- docs/userguide/src/site/pages/thredds/GribConfigRef.md
Update documentation about interval coordinate values to reflect change made from endpoint to midpoint in [netcdf-java gh #1035](https://github.com/Unidata/netcdf-java/pull/1035)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/270)
> Update documentation about interval coordinate values

- tds-ugrid/src/main/java/ucar/nc2/dt/UGridDatatype.java
- tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/MeshVariable.java
- tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/UGridDataset.java
- tds-ugrid/src/main/resources/META-INF/services/ucar.nc2.dt.grid.internal.spi.GridDatasetProvider
- tds/build.gradle
- tds/src/integrationTests/java/ucar/nc2/dt/fmrc/TestUgridFmrc.java
- tds/src/test/content/thredds/catalog.xml
- tds/src/test/content/thredds/catalogFmrc.xml
Enable Forecast Model Run Collections for data following the UGRID
conventions. The following services are supported:
* OPeNDAP
* HTTPServer
* CDMRemote
* THREDDS ISO Services (iso, ncml, uddc)
* WMS
Support for NCSS will be added in a future update.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/272)
> Support UGRID FMRCs in the TDS

- tds/src/main/java/thredds/server/dap4/Dap4Controller.java
DAP4 is not completely working yet and so we have removed it from `netcdfAll`. However, recently a user reported lots of errors from TDS when using DAP4, so it is still apparently allowed to be configured and used from TDS.
This PR would throw an exception when DAP4 is used from TDS, so that hopefully it is clearer that it is not yet functional, but we are working on it. Suggestions for better messages welcome!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/288)
> Throw an exception when using DAP4 until we get it functional

- docs/adminguide/src/site/pages/thredds/ThreddsConfigRef.md
- docs/devguide/src/site/pages/thredds/ThreddsConfigRef.md
- docs/quickstart/src/site/pages/thredds/ThreddsConfigRef.md
- docs/userguide/src/site/pages/tds_tutorial/feature_collections/FmrcRef.md
- docs/userguide/src/site/pages/thredds/ThreddsConfigRef.md
After a recent issues involving the FMRC cache settings (https://github.com/Unidata/tds/issues/275), I wanted to try to add extra info and clarify the documentation about these settings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/289)
> Add more info about chronicle map cache configuration parameters

- build.gradle
- gradle/any/gretty.gradle
- gradle/any/shared-mvn-coords.gradle
- gradle/root/publishing.gradle
Gradle's plugin portal can use JCenter, which is being shutdown this year so is no longer reliable (https://blog.gradle.org/jcenter-shutdown).
This PR implements the workaround in the discussion [here](https://github.com/gradle/gradle/issues/15406), which is to just put `mavenCentral` first in the list of repos to check. So since I am leaving the `gradlePluginPortal` as the fallback option, I don't think this PR can break anything.
The second change is just a bump of Gretty's minor version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/290)
> Upgrade gretty and use mavenCentral

- tds/src/integrationTests/java/thredds/server/fileserver/TestFileServer.java
Upgrading gretty from 3.0.3 to 3.0.9 changed the content type that fileserver returns in its header for json from `application/json;charset=UTF-8` to `application/json`. I don't think this matters, the other content types never mentioned the charset.
This change would fix two failing tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/292)
> Update content type expected in test

- tds/src/integrationTests/java/thredds/server/wms/TestUpdateWmsServer.java
- tds/src/main/java/thredds/server/wms/ThreddsWmsServlet.java
If you update a file, it does not update the output you get through WMS, since this is cached in a map with the key as the file name.
This PR checks the last modified date of the file against the cache in order to check if WMS catalogue cache is current, and if it is not then updates it. I also added an automated test for this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/294)
> WMS should not use outdated cache

- tds/build.gradle
See unidata/tds#194 (specifically https://github.com/Unidata/tds/issues/194#issuecomment-1270778988).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/297)
> Add runtime support for AWS Security Token Service

- docs/userguide/src/site/pages/tds_tutorial/faq/faq.md
- tds/src/main/webapp/WEB-INF/classes/log4j2.xml
After the discussion in https://github.com/Unidata/tds/issues/194, it seems useful to log aws sdk warnings and higher. In addition, I added a note to the FAQs about how to change log settings for debugging object store requests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/298)
> Add log messages for aws sdk

- tdcommon/src/main/java/thredds/server/catalog/ConfigCatalog.java
- tdcommon/src/main/java/thredds/server/catalog/builder/CatalogScanBuilder.java
- tdcommon/src/main/java/thredds/server/catalog/builder/FeatureCollectionRefBuilder.java
- tds/src/main/java/thredds/core/CatalogManager.java
Remove hardcoded "thredds" context and instead pass in correct context from `tdsContext` when building featureCollection or catalogScan.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/301)
> Remove hardcoded thredds context

- gradle/any/shared-mvn-coords.gradle
- tds/build.gradle
- exclude netty from dependencies to avoid CVES
- upgrade protobuf to match netcdf-java
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/303)
> upgrade protobuf and exclude netty from AWS deps

- tds/src/main/java/thredds/core/DatasetManager.java
- tds/src/test/content/thredds/catalog.xml
- tds/src/test/java/thredds/server/fileserver/FileServerControllerTest.java
- tds/src/test/java/thredds/server/ncss/controller/grid/GridDatasetControllerTest.java
Fix FileNotFound error that occurred when a ncml dataset had a urlPath with a prefix that happened to be a featureCollection path.
- Switch the order of lookup: first check if there is a ncml location before doing anything with the urlPath, such as checking it for featureCollection roots or datasetRoots
- Add tests for this
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/306)
> Fix ncml location lookup

- docs/userguide/src/site/pages/thredds/NcssPoint.md
- docs/userguide/src/site/pages/thredds/NcssRef.md
- tds/src/integrationTests/java/thredds/server/ncss/NcssGridIntegrationTest.java
- tds/src/main/java/thredds/server/ncss/controller/NcssGridController.java
- tds/src/main/java/thredds/server/ncss/format/SupportedFormat.java
In PR https://github.com/Unidata/tds/pull/307, I mistakenly thought accept parameter `netcdf4` should refer to the extended netcdf4, when it should refer to the netcdf4-classic. This PR fixes the accept parameters and the documentation about that.
In addition, I did one small cleanup to make the SupportedFormat class clearer-- when checking if an accept parameter `isAlias` for one of the formats, the `formatName` and list of aliases are checked, so the `formatName` does not need to be repeated in the aliases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/308)
> Fix accept parameters

- tds/src/integrationTests/java/thredds/server/wms/TestWmsServer.java
- tds/src/test/content/thredds/catalog.xml
Add test for WMS GetMap for an aggregation dataset variable that does not depend on aggregation dimension. This tests fix in https://github.com/Unidata/edal-java/pull/4
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/309)
> Add test for WMS for aggregation issue

- docs/userguide/src/site/pages/thredds/ThreddsConfigRef.md
Change the example `<dir>` to not have a variable as this will not be substituted. If this example gets copy/pasted, this is confusing because there will be a directory created called `${tds.content.root.path}/thredds/...`. This is in line with what is already shown for `WCS` and `NetcdfSubsetService`, and the default values are written below.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/319)
> Improve cache documentation

- tds/src/main/java/thredds/server/wms/TdsWmsDatasetFactory.java
- tds/src/main/java/thredds/server/wms/ThreddsWmsCatalogue.java
- tds/src/main/java/thredds/server/wms/ThreddsWmsServlet.java
- tds/src/test/content/thredds/catalogUpdateAgg.xml
- tds/src/test/java/thredds/server/wms/TestWmsCache.java
This PR addresses the issue with WMS not updating its cache for aggregations with a scan with a `recheckEvery` attribute.
Previously, the cache was getting the date last modified by looking at the date last modified of a `File` with the location from the request, which does not work for aggregations (or S3 files), so the date last modified was always -1 and the cached file was always used. This PR instead uses the date last modified from the underlying `NetcdfDataset`, which in the case of an aggregation, will rescan the files according to the `recheckEvery`.
The `NetcdfDataset::getLastModified` I am using here overrides the deprecated method `NetcdfFile::getLastModified`. I am not sure why that is deprecated or if that is a problem?
I am going to try to fix the date last modified for S3 …
> Fix wms cache for aggregations

- docs/userguide/src/site/pages/tds_tutorial/faq/faq.md
- docs/userguide/src/site/pages/thredds/ThreddsConfigRef.md
- tds/src/main/java/thredds/featurecollection/cache/GridInventoryCacheChronicle.java
- tds/src/main/java/thredds/server/admin/DebugCommands.java
- tds/src/main/java/thredds/server/config/TdsInit.java
- tds/src/test/content/thredds/threddsConfig.xml
- tds/src/test/java/thredds/featurecollection/cache/TestGridInventoryCacheChronicle.java
- tds/src/test/java/thredds/server/config/ThreddsConfigTest.java
Related to https://github.com/Unidata/tds/issues/317.
- Add `averageValueSize` parameter to the FMRC cache settings in `threddsConfig.xml`, with values: small (default), medium, or large.
- Use compact xml in the cache instead of pretty printed xml
- Update documentation
- Add tests (added a file to thredds-test-data that has a large cache value size)
- Add extra logging info to the admin debug service
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/327)
> Add averageValueSize to chronicle map cache

- tds/src/test/java/thredds/server/ncss/controller/grid/GridDatasetControllerTest.java
Add test that cache resources get released when an NCSS request throws an exception.
Depends on fix in https://github.com/Unidata/netcdf-java/pull/1120 for tests to pass.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/329)
> Add test that cache resources are released

- tdcommon/build.gradle
- tdcommon/src/main/java/thredds/server/catalog/tracker/DatasetExtBytesMarshaller.java
- tds-platform/build.gradle
- tds/src/test/java/thredds/featurecollection/cache/TestGridInventoryCacheChronicle.java
In addition to the chronicle map update, we updated the chronicle map cache tests to be less strict. The updated version of chronicle map did not fit the same number of entries in the cache for the same settings. However, it's probably more important to test that it initializes and fits the right order of magnitude of entries than to test the precise details, so we made the test asserts less strict. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/331)
> Update Chronicle-Map (as part of JNA update)

- tds/src/integrationTests/java/thredds/featurecollection/TestGribFeatureCollection.java
- tds/src/main/java/thredds/featurecollection/InvDatasetFcGrib.java
Fixes issue where grib collections with one time dimension always return all times even when a single file is requested.
The function I am fixing in this PR should return the full collection when the "TP" is requested and null if a specific grib file is requested (and then a different code path will find the correct time partition to return instead of the whole thing). Previously, it returned the full dataset in both cases. This bug did not affect forecast datasets that have two time dimensions, because there the number of datasets is two (best and twoD).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/339)
> Fix grib collection time interval

- docs/userguide/src/site/pages/thredds/ThreddsConfigRef.md
Remove documentation references to /WEB-INF/palettes which no longer exist in TDS 5.
See https://github.com/Unidata/tds/issues/173#issuecomment-956943943 or commit 3335c3632bfc416672c21bd0a2c1c332e5978273
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/342)
> Update docs about wms palettes

- docs/userguide/src/site/pages/thredds/ThreddsConfigRef.md
- tds/src/main/java/thredds/server/ncss/controller/NcssGridController.java
- Delete file from NCSS cache when a request succeeds instead of waiting for scour task to clean it up
- Update NCSS and WCS threddsConfig.xml docs to have correct default values
- Minor cleanups: spelling, delete unused parameters
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/348)
> Ncss cache fixes

- tds/src/test/java/thredds/server/ncss/controller/grid/GridCoverageSubsettingTest.java
- Clean up test class-- use google truth asserts, remove commented out code, style fixes, remove print statements 
- Add tests for NCSS with full longitude request and either full or partial latitudes requested. This tests issue: https://github.com/Unidata/tds/issues/315. Note tests are not being run on GitHub due to `NeedsCdmUnitTest` flag. Newly added tests depend on fix: https://github.com/Unidata/netcdf-java/pull/1167 to pass.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/354)
> Test longitude subsetting in NCSS

- docs/adminguide/src/site/pages/installation_upgrade/JVMSettings.md
- docs/devguide/src/site/pages/tds_tutorial/getting_started/RunningTomcat.md
- docs/quickstart/src/site/pages/tds_tutorial/getting_started/RunningTomcat.md
- docs/userguide/src/site/pages/tds_tutorial/getting_started/RunningTomcat.md
Remove enable asserts `-ea` from JAVA_OPTS in docs as this can be bad for performance (we had a support issue where it caused slow WMS performance)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/377)
> Remove enable asserts from docs

- opendap/dtswar/src/main/java/opendap/dts/DTSServlet.java
- opendap/server/src/main/java/opendap/servers/parsers/AST.java
- opendap/server/src/main/java/opendap/servers/parsers/Ceparse.java
We have removed the enable asserts option from our TDS servers. So asserts should not be used for error handling. This PR:
- Changes assert(false) to an exception
- Removes some null checks/asserts where the variable actually can't be null (this change may be clearer if you hide whitespace differences)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/380)
> Improve code with asserts

- tds/src/integrationTests/java/thredds/server/cdmr/TestCdmRemoteCompareDataP.java
- tds/src/integrationTests/java/thredds/server/cdmr/TestCdmRemoteMisc.java
- tds/src/integrationTests/java/thredds/server/dap4/TestDap4.java
Currently four tests are failing on Jenkins (and have been for a long time). This PR would ignore three of them.
- `testSimpleDap4GridDataset` since DAP4 is still a work in progress in the TDS
- `testVlenInStructure` and `TestCdmRemoteCompareDataP ::doOne` with file `IntTimSciSamp.nc`-- both involve the same file that has a vlen structure member. I encountered issues with this same file while working on the gCDM and discovered that netcdf-java simply does not work for structures with vlens, so I had to ignore this file in the gCDM tests as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/381)
> Ignore tests

- tds-ugrid/src/test/resources/cases/fvcom/fvcom_delt.ncml
Fix [failing test](https://jenkins-aws.unidata.ucar.edu/job/tds/255/testReport/junit/ucar.nc2.dataset/UGridConventionIntegrationTest/classMethod/) after https://github.com/Unidata/netcdf-java/pull/1209. The test ncml file renames the dimension but does not update the name of the dimension in the variables that use it, which causes an error since those variables use a non-existent dimension. The tests don't use the renamed dimension, so I just removed the rename here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/393)
> Fix test file that renames dimension

- .gitignore
- docs/userguide/src/site/pages/tds_tutorial/tds_configuration/CustomizingTdsLookAndFeel.md
- tds/src/integrationTests/java/thredds/server/notebook/TestNotebookServices.java
- tds/src/main/java/thredds/server/notebook/NotebookController.java
- tds/src/main/java/thredds/server/notebook/NotebookMetadata.java
- tds/src/test/content/thredds/notebooks/testNotebookMetadata.ipynb
- tds/src/test/data/testNotebookMetadata.json
- tds/src/test/java/thredds/server/notebook/TestNotebookService.java
The motivation for this change is to configure notebooks for specific datasetScans or featureCollections. For instance, a datasetScan with ID of `myDatasetScanId` contains datasets with IDs of `myDatasetScanId/filename.nc` so an exact match on ID doesn't help you for that case.
This PR includes:
- Allow regular expressions in the `accept_datasetIDs` strings
- integrations tests for the notebook service
- unit tests for regular expressions
- add example to documentation
- return a 404 error for dataset not found
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/401)
> Allow regExp in notebook lookup by datasetID

- tds/src/main/java/thredds/server/notebook/JupyterNotebookViewerService.java
- tds/src/main/java/thredds/server/wms/Godiva3Viewer.java
- tds/src/test/java/thredds/server/notebook/TestNotebookService.java
- tds/src/test/java/thredds/server/wms/TestGodiva3Viewer.java
Need to encode Godiva and Jupyter URLs to handle special characters in the file names.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/417)
> Encode Godiva and Jupyter urls

- tds/src/main/java/thredds/server/TdsErrorHandling.java
Do not include complete message with a FileNotFound exception-- it will be logged
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/421)
> Update FileNotFound message info

- tds/src/test/java/thredds/server/ncss/controller/grid/GridDatasetControllerTest.java
Use `assertWithMessage` to give more info when the test fails.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/425)
> Improve error message when test fails

- project-files/downloads-page/release_info.json
- project-files/startup/latest.xml
- tds/src/test/java/thredds/server/config/TdsContextTest.java
Add current `release_info.json` and `latest.xml` files from nexus to git repo. The first is used for the downloads page on the website and the second prints info about current TDS versions upon startup. Will update these in a next PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/426)
> Add release_info.json and latest.xml files

- project-files/downloads/release_info.json
I already tested publishing this so you can see what it looks like here: https://downloads.unidata.ucar.edu/tds/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/428)
> Add thredds iso plugin to downloads page

- tds/src/main/java/thredds/core/DatasetManager.java
- tds/src/test/content/thredds/catalog.xml
- tds/src/test/java/thredds/server/ncss/controller/grid/NcmlTest.java
Resolves https://github.com/Unidata/tds/issues/398.
- refactor dataset scans with ncml code in `openNetcdfFile` to helper function
- Handle dataset scans with ncml in `openCoverageDataset` (used by NCSS)
- Small fix for `openCoverageDataset` code-- don't perform null check when function returns `@NonNull`
- Add tests. Update catalog ncml to work for NCSS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/434)
> Use ncml in dataset scans opened through ncss

- tds/src/integrationTests/java/thredds/server/services/TestEnhancements.java
- tds/src/test/content/thredds/catalog.xml
Enhancements seem to be working in NCSS for NcML datasets if you give a numeric type (other [PR ](https://github.com/Unidata/tds/pull/434) to fix datasetScans). Unignore test and make NcML offset type float instead of string so the offset is recognized.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/435)
> Update enhancements test 

- tds/src/integrationTests/java/thredds/tds/TestS3Ncml.java
Add tests for fix in https://github.com/Unidata/netcdf-java/pull/1277. Depends on that PR being merged to pass.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/438)
> Add tests for opening a ncml dataset on S3

- tds/src/integrationTests/java/thredds/tds/TestS3Ncml.java
- Add test for opening an ncml file with xml extension
- change expected behavior for file with extension other than xml or ncml (changed in https://github.com/Unidata/netcdf-java/pull/1281)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/440)
> Update s3 ncml tests

- .github/workflows/tds.yml
Fix typo in GitHub workflow in the test failure artifact name
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/443)
> Fix test artifact name

- tds/src/integrationTests/java/thredds/server/services/TestEnhancements.java
- tds/src/integrationTests/java/thredds/server/wms/TestWmsServer.java
- tds/src/test/content/thredds/catalog.xml
Ensure both the case of variable enhancement attributes (such as add_offset) in a file and in NcML are tested for NCSS, Opendap, and WMS:
- NCSS: both cases already present in `TestEnhancements`
- Opendap: add both cases to `TestEnhancements` in this PR. Also added NcML `enhance=none` case.
- WMS: enhancement from file already tested in `TestWmsServer`, NcML enhancement test added in this PR
For the situation tested, NCSS and WMS apply enhancements for both inherent attributes and NcML. Opendap applies the enhancements for NcML when `enhance=all` is specified but not if `enhance=none` is specified. Opendap does not apply inherent enhancements to data (so it provides packed binary data).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Test Opendap and WMS are applying enhancements correctly

- tds/src/integrationTests/java/thredds/tds/TestZarr.java
Closes https://github.com/Unidata/tds/issues/444. Depends on changes in https://github.com/Unidata/netcdf-java/pull/1285.
Unignore zarr s3 test and add trailing delimiter to path.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/447)
> Update zarr s3 test

- tds-platform/build.gradle
- tds-testing-platform/build.gradle
- tds/build.gradle
- tds/src/main/java/thredds/server/catalogservice/CatalogViewContextParser.java
TDS is not compiling due to missing apache commons-lang 2.0 dependency used in `CatalogViewContextParser`. I _think_ what happened is this used to be pulled in by edal-java but they updated to 3.x. So here I update TDS to use `org.apache.commons:commons-lang3` but also to explicitly declare it as a dependency.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/452)
> Add apache dependency

- tds/src/integrationTests/java/thredds/tds/TestZarr.java
Add test hitting the same zarr file twice to ensure it works correctly with the netcdf file cache. This test depends on fix in https://github.com/Unidata/netcdf-java/pull/1288
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/450)
> Add extra test for zarr and caching

- tds/src/integrationTests/java/thredds/server/ncss/TestGridAsPointP.java
- tds/src/integrationTests/java/thredds/server/services/ConsistentDatesTest.java
- tds/src/test/java/thredds/server/ncss/controller/gridaspoint/TestGridAsPointMisc.java
In addition to tests ignored in https://github.com/Unidata/tds/pull/442, ignore three test cases failing on Jenkins due to cfpointwriters
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/451)
> Ignore cfpointwriter tests

- .github/workflows/deps.yml
- .github/workflows/docs.yml
- .github/workflows/style.yml
- .github/workflows/tds.yml
- .github/workflows/update-docker.yml
Update the deprecated github checkout action from v2 to v4
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/454)
> Update GitHub action

- tds/src/integrationTests/java/thredds/server/wms/TestWmsServer.java
- tds/src/main/java/thredds/server/config/TdsInit.java
Fix wms epsg database not loading issue (should fix https://github.com/Unidata/tds/issues/455)
- Add wms get map test that uses EPSG:3857 which requires the epsg database. This did not reproduce the issue for me locally, but I thought it was still useful to have as a test.
- Remove `toURI()` from epsg database path. This is because edal-java now expects a file path, not a URI path.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/457)
> Fix wms epsg database not loading

- docs/userguide/src/site/pages/tds_tutorial/tds_configuration/AddingOgcIsoServices.md
Add section to ncISO documentation for where to put your custom xsl file
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/458)
> Improve ncISO documentation

- docs/adminguide/src/site/_data/sidebars/admin_sidebar.yml
- docs/devguide/src/site/_config.yml
- docs/devguide/src/site/_data/sidebars/dev_sidebar.yml
- docs/quickstart/src/site/_data/sidebars/quickstart_sidebar.yml
- docs/shared/src/site/_data/topnav.yml.golden
- docs/userguide/src/site/_config.yml
- docs/userguide/src/site/_data/sidebars/user_sidebar.yml
- gradle/root/publishing.gradle
- project-files/docs/version-info.json
Add `version-info.json` used in TDS docs to repo and add gradle task to deploy to nexus
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/459)
> Update versions in docs

- tds/src/integrationTests/java/thredds/server/wms/TestUpdateWmsServer.java
- tds/src/main/java/thredds/server/admin/DebugCommands.java
- tds/src/main/java/thredds/server/wms/TdsWmsDatasetFactory.java
- tds/src/main/java/thredds/server/wms/ThreddsWmsCatalogue.java
- tds/src/main/java/thredds/server/wms/ThreddsWmsServlet.java
- tds/src/test/java/thredds/server/wms/TestWmsCache.java
Currently, when a dataset is opened through WMS, it stays locked in the netcdf file cache. This means the file will never be cleaned up in the cache, since the soft limit does not apply to locked files and the hard limit is set to -1 (no limit) by default.
This PR:
- Use try with resources in wms to ensure netcdf file gets closed and does not stay locked.
- Use guava cache instead of map for WMS cache
- Update tests and add tests ro check if file is locked in the netcdf file cache after a wms request
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/461)
> Fix WMS netcdf file locking issue

- docs/userguide/src/site/pages/tds_tutorial/production/Upgrade.md
Maybe its useful to eventually spell out specific things that changed from TDS 4 to 5 in terms of WMS/godiva, but I thought at least for now we can mention that the ncWMS library changed and point to their documentation.
> Add wms info to upgrade guide in documentation

- tds/src/main/java/thredds/server/wms/ThreddsWmsServlet.java
- tds/src/test/java/thredds/server/wms/TestWmsCache.java
Only use cached file if last modified is an exact match. This fixes the case that a file is updated but with an older last modified date than before, and so the cached file continued to be used. This fix also makes the behavior the same for the WMS cache and the NetcdfFile cache, so all the services should behave the same when it comes to checking the last modified.
> Wms cache last modified comparison

- docs/userguide/src/site/pages/thredds/ThreddsConfigRef.md
- tds/src/main/java/thredds/server/config/TdsConfigMapper.java
- tds/src/main/java/thredds/server/config/WmsConfigBean.java
Resolves https://github.com/Unidata/tds/issues/468
Manually tested the default style directory and a custom directory
> Add styles directory to WMS config

- tds/src/integrationTests/java/thredds/server/ncss/NcssGridIntegrationTest.java
- tds/src/test/content/thredds/catalogGrib.xml
Add test for bug that missing variable in one grib partition caused NaNs for all times after. Added one day's worth of RTMA data to thredds-test-data. Test originally failed (on Jenkins, won't run on GitHub), now passes with fix from: https://github.com/Unidata/netcdf-java/pull/1313
> Add test for grib NaN issue

- docs/userguide/src/site/pages/thredds/ThreddsConfigRef.md
Fix documentation about how to disable the scour in an AggregationCache to use a unit so it will be parsed
> Fix cache scour documentation 

- tds/src/main/java/thredds/server/wms/ThreddsWmsServlet.java
Exceptions are getting wrapped by WMS cache loader as `UncheckedExecutionException`s. For edal-java not to return a 500 error, we want these to be unwrapped back into `EdalException`s. Previously I accidentally was nested these inside a new `EdalException` leading to less helpful error messages. This PR returns original exception instead of wrapping them.
> Fix WMS exception messages

- dap4/d4servlet/build.gradle
- dap4/d4ts/build.gradle
- gradle/root/publishing.gradle
- opendap/dtswar/build.gradle
- opendap/server/build.gradle
- tdm/build.gradle
- tds-test-utils/build.gradle
- tds-ui/build.gradle
Use two spaces instead of four for indents in gradle files. I tried to get spotless to enforce this but I don't think that's possible for gradle files.
> Gradle whitespace fixes

- dap4/d4servlet/src/main/java/dap4/servlet/CDMWrap.java
- dap4/d4servlet/src/main/java/dap4/servlet/ChunkWriter.java
- dap4/d4servlet/src/main/java/dap4/servlet/DapController.java
Fix javadoc warnings about invalid use of tags
> Fix javadoc warnings

- tds/src/integrationTests/java/ucar/nc2/dt/grid/TestGridSubsetThredds.java
- tds/src/test/java/thredds/server/wms/TestWmsCache.java
- Ignore test that requires external server that is unavailable
- Improve before/after steps of test that checks NetcdfFile cache. Currently this can fail if run after certain tests that leave files locked in the NetcdfFile cache.
> Improve tests

- tds/src/integrationTests/java/thredds/server/catalog/TestServiceDefaults.java
- tds/src/main/java/thredds/core/CatalogManager.java
- tds/src/test/content/thredds/catalogs5/testServices.xml
Resolves https://github.com/Unidata/tds/issues/352.
When a dataset catalog entry has a `dataType` set, standard services should get assigned.  Previously only top level datasets would get standard services. This PR also handles child dataset nodes recursively when assigning standard services.
> Fix standard services for nested datasets

- opendap/dtswar/src/main/java/opendap/dts/DTSServlet.java
- opendap/server/src/main/java/opendap/servers/CEEvaluator.java
- opendap/server/src/main/java/opendap/servers/SDSequence.java
- opendap/server/src/main/java/opendap/servlet/AbstractServlet.java
- tds/src/main/java/thredds/server/admin/AdminLogController.java
- tds/src/main/java/thredds/servlet/ServletUtil.java
Minor improvements:
- Fix unchecked compiler warnings by using parametrized containers
- Use expression lambda instead of statement lambda
> Fix warnings

- docs/userguide/src/site/pages/tds_tutorial/production/Upgrade.md
On the upgrade page, link to required java/tomcat versions on install page instead of keeping these version numbers in sync in two places.
> Improve upgrade docs

- tds-platform/build.gradle
Upgrade to chronicle-bom 2.25ea62 (release versions no longer published on maven). This contains chronicle-map version 3.25ea6, which has fix needed in https://github.com/Unidata/tds/issues/484. Passes tests on Jenkins: https://jenkins-aws.unidata.ucar.edu/view/Users/job/tara-tds/37/
> Upgrade chronicle

- dap4/d4servlet/src/main/java/dap4/servlet/CDMWrap.java
- opendap/dtswar/src/main/java/opendap/dts/Getopts.java
- opendap/dtswar/src/main/java/opendap/dts/SDTest.java
- opendap/server/src/main/java/opendap/servlet/AsciiWriter.java
- opendap/server/src/main/java/opendap/servlet/ascii/asciiByte.java
- opendap/server/src/main/java/opendap/servlet/ascii/asciiF32.java
- opendap/server/src/main/java/opendap/servlet/ascii/asciiF64.java
- opendap/server/src/main/java/opendap/servlet/ascii/asciiI16.java
- opendap/server/src/main/java/opendap/servlet/ascii/asciiI32.java
- opendap/server/src/main/java/opendap/servlet/ascii/asciiUI16.java
- opendap/server/src/main/java/opendap/servlet/ascii/asciiUI32.java
Fix compiler warnings about using deprecated boxing constructors. Instead use the static `valueOf` or let the primitives be auto boxed.
> Fix compiler warnings

- tds/src/integrationTests/java/thredds/server/services/ConsistentDatesTest.java
- tds/src/main/java/thredds/core/DatasetManager.java
- tds/src/main/java/thredds/server/ncss/view/dsg/station/AbstractStationProfileSubsetWriter.java
- tds/src/main/java/thredds/server/ncss/view/dsg/station/StationProfileSubsetWriterNetcdf.java
- tds/src/test/java/thredds/server/ncss/controller/gridaspoint/TestGridAsPointMisc.java
- tds/src/test/java/thredds/server/ncss/view/dsg/DsgSubsetWriterTest.java
- tds/src/test/resources/thredds/server/ncss/view/dsg/point/netcdf3/outputAll.ncml
- tds/src/test/resources/thredds/server/ncss/view/dsg/point/netcdf3/outputSubset.ncml
- tds/src/test/resources/thredds/server/ncss/view/dsg/point/netcdf4/outputAll.ncml
- tds/src/test/resources/thredds/server/ncss/view/dsg/point/netcdf4/outputSubset.ncml
- tds/src/test/resources/thredds/server/ncss/view/dsg/station/netcdf3/outputAll.ncml
- tds/src/test/resources/thredds/server/ncss/view/dsg/station/netcdf3/outputSubset1.ncml
- tds/src/test/resources/thredds/server/ncss/view/dsg/station/netcdf3/outputSubset2.ncml
- tds/src/test/resources/thredds/server/ncss/view/dsg/station/netcdf4/outputAll.ncml
- tds/src/test/resources/thredds/server/ncss/view/dsg/station/netcdf4/outputSubset1.ncml
- tds/src/test/resources/thredds/server/ncss/view/dsg/station/netcdf4/outputSubset2.ncml
- tds/src/test/resources/thredds/server/ncss/view/dsg/station_profile/input.ncml
- tds/src/test/resources/thredds/server/ncss/view/dsg/station_profile/netcdf3/outputAll.ncml
- tds/src/test/resources/thredds/server/ncss/view/dsg/station_profile/netcdf3/outputSubset1.ncml
- tds/src/test/resources/thredds/server/ncss/view/dsg/station_profile/netcdf3/outputSubset2.ncml
- tds/src/test/resources/thredds/server/ncss/view/dsg/station_profile/netcdf4/outputAll.ncml
- tds/src/test/resources/thredds/server/ncss/view/dsg/station_profile/netcdf4/outputSubset1.ncml
- tds/src/test/resources/thredds/server/ncss/view/dsg/station_profile/netcdf4/outputSubset2.ncml
- turn DSG subset writer tests back after fixes to CFPointWriter and Point feature classes
> Enable tests

- build.gradle
- dap4/d4ts/build.gradle
- gradle/any/shared-mvn-coords.gradle
- gradle/wrapper/gradle-wrapper.properties
- opendap/dtswar/build.gradle
- opendap/server/build.gradle
- tdcommon/build.gradle
- tdm/build.gradle
- tds-ugrid/build.gradle
- tds-ui/build.gradle
- tds/build.gradle
Upgrade gradle from 6.9.1 to 7.6.4.
Note: wait to merge this til after 5.5 release.
> Upgrade gradle

- .github/workflows/deps.yml
- .github/workflows/docs.yml
- .github/workflows/style.yml
- .github/workflows/tds.yml
- docs/userguide/src/site/pages/tds_tutorial/faq/faq.md
- docs/userguide/src/site/pages/tds_tutorial/getting_started/InstallJavaTomcat.md
- docs/userguide/src/site/pages/tds_tutorial/getting_started/RunningTomcat.md
- gradle/any/java-internal.gradle
- gradle/any/properties.gradle
- tdcommon/build.gradle
- tds/build.gradle
- Update JDK from 11 to 17.
- Update GitHub workflows-- note Zulu 17 is present but not currently working in the thredds-test-environment
- Add JVM arguments needed by chronicle to tests and gretty: https://chronicle.software/chronicle-support-java-17/
- Add JVM args to documentation
> Update to JDK 17

- gradle/any/dependencies.gradle
Sonatype is getting tried for Unidata's artifacts, and is now suddenly returning a 502 error which prevents netcdf-java artifacts from getting downloaded. This PR:
- switches order of repos so our artifacts can be found on nexus and sonatype is used last
- limited use of sonatype to chronicle artifacts
> Switch order of dependency repos

- docs/adminguide/src/site/pages/installation_upgrade/JVMSettings.md
Fix JVM option path in documentation-- the `$CONTENT_ROOT` in the `JAVA_PREFS_ROOTS` should be `/data/content` not `-Dtds.content.root.path=/data/content`.
> Fix JVM option path in documentation

- dap4/d4servlet/build.gradle
- dap4/d4servlet/src/main/java/dap4/servlet/DapDSR.java
- dap4/d4ts/src/main/webapp/WEB-INF/templates/dap4.dsr.html.template
- tds/src/main/webapp/WEB-INF/templates/dap4.dsr.html.template
- Use apache's string escape utils to escape html in user inputted values
- Fix unrelated html typos in template files
> Fix html encoding

- tds-platform/build.gradle
Switch back to last edal-java release instead of snapshot so things don't break when I do edal-java jakarta servlet upgrades.
> Use last edal-java release

- README.md
- docs/adminguide/src/site/pages/overview/TDSVetted.md
- docs/userguide/src/site/_config.yml
Emphasize GitHub as primary avenue of support, while eSupport can still be used for security issues.
> Improve support documentation

- tds/src/main/webapp/WEB-INF/templates/gridFragments.html
- tds/src/main/webapp/WEB-INF/templates/pointFragments.html
As in this [issue](https://github.com/Unidata/netcdf-java/pull/1162), NCSS cannot handle commas as decimal separators. Depending on your browser's locale, the default lat/lon range may use commas as the decimal separator which will not work with the bean validation. This PR makes thymeleaf display the default lat/lon bounds using points as the decimal separator regardless of browser settings.
> Fix NCSS decimal separators

- tds/src/main/java/thredds/server/opendap/OpendapServlet.java
- tds/src/main/java/thredds/server/wfs/WFSController.java
- Do not include file paths in open dap's 404 exception messages 
- Fix Coverity flagged issue on WFS exception containing query parameters
> Improve exception messages

- tds/src/integrationTests/java/thredds/server/radar/TestRadarServerQuery.java
- tds/src/main/java/thredds/server/radarServer2/RadarServerConfig.java
- tds/src/test/content/thredds/radar/CS039_L2_stations.xml
- tds/src/test/content/thredds/radar/radarCollections.xml
- tds/src/test/java/thredds/util/xml/XmlUtil.java
- Add tests for radar server queries using existing level2 and level3 data in cdmUnitTest datasets
- Fix level2 test dataset config so it matches current data, by adding a station and fixing date format
- Add xml util test function
- Use the Alias translator in the `RadarServerConfig` so test datasets with `${cdmUnitTest}` path variable get translated to a path
> Add radar server tests

- tds/src/main/java/thredds/util/TdsPathUtils.java
Allow file names with two periods like "my..file.nc". To ensure no traversal to parent directory, we will disallow "../".
> Allow two periods in file paths

- docs/userguide/src/site/pages/tds_tutorial/getting_started/RunningTomcat.md
Fix JVM option path in documentation-- the `$CONTENT_ROOT` in the `JAVA_PREFS_ROOTS` should be `/data/content` not `-Dtds.content.root.path=/data/content`.
Same change as: https://github.com/Unidata/tds/pull/518
> Update JVM args in docs

- tds/src/integrationTests/java/thredds/server/radar/TestRadarServer.java
- tds/src/integrationTests/java/thredds/server/radar/TestRadarServerQuery.java
- tds/src/main/java/thredds/server/radarServer2/RadarDataInventory.java
- tds/src/main/java/thredds/server/radarServer2/RadarServerConfig.java
- tds/src/main/java/thredds/server/radarServer2/RadarServerController.java
- tds/src/test/content/thredds/radar/radarCollections.xml
Resolves https://github.com/Unidata/tds/issues/361 and depends on functionality added in https://github.com/Unidata/netcdf-java/pull/1388.
Make RadarServer code work for S3 datasets by:
- Using `MFile` interface (which has implementations for local and s3 files) instead of a `Path` object
- Using `MController` interface to loop through directories/files (which has implementations for local and S3 files) instead of a `DirectoryStream`
Tests:
- Duplicates test catalog entry for radar data but pointing to s3 version
- Adds s3 test cases to radar server tests
> S3 radar server

- tds/src/main/java/thredds/server/config/TdsInit.java
Address https://github.com/Unidata/tds/issues/455. Revert change (https://github.com/Unidata/tds/pull/457) in path for loading the EPSG database. The change was needed due to a change in edal-java, which has now been reverted: https://github.com/Unidata/edal-java/pull/13.
> Revert change to database path

- docs/adminguide/src/site/pages/tds_tutorial/tds_configuration/AddingNcss.md
- docs/adminguide/src/site/pages/tds_tutorial/tds_configuration/ConfigCatalog.md
- docs/adminguide/src/site/pages/thredds/TdsServices.md
- docs/adminguide/src/site/pages/thredds/ViewersRef.md
- docs/devguide/src/site/pages/tds_tutorial/tds_configuration/AddingNcss.md
- docs/devguide/src/site/pages/tds_tutorial/tds_configuration/AddingOgcIsoServices.md
- docs/devguide/src/site/pages/tds_tutorial/tds_configuration/ConfigCatalog.md
- docs/devguide/src/site/pages/thredds/TdsServices.md
- docs/devguide/src/site/pages/thredds/ViewersRef.md
- docs/quickstart/src/site/pages/tds_tutorial/production/Upgrade.md
- docs/quickstart/src/site/pages/tds_tutorial/tds_configuration/AddingNcss.md
- docs/quickstart/src/site/pages/tds_tutorial/tds_configuration/AddingOgcIsoServices.md
- docs/quickstart/src/site/pages/tds_tutorial/tds_configuration/ConfigCatalog.md
- docs/quickstart/src/site/pages/thredds/TdsServices.md
- docs/quickstart/src/site/pages/thredds/ViewersRef.md
- docs/userguide/src/site/pages/tds_tutorial/production/Upgrade.md
- docs/userguide/src/site/pages/tds_tutorial/tds_configuration/AddingNcss.md
- docs/userguide/src/site/pages/tds_tutorial/tds_configuration/AddingOgcIsoServices.md
- docs/userguide/src/site/pages/tds_tutorial/tds_configuration/ConfigCatalog.md
- docs/userguide/src/site/pages/thredds/TdsServices.md
- docs/userguide/src/site/pages/thredds/ViewersRef.md
Call out changes to NCSS service elements in 5.x (i.e. GRID and POINT have different service elements). Addresses Unidata/tds#544.
> Improve NCSS docs and upgrade guide

- docs/adminguide/src/site/pages/thredds/ThreddsConfigRef.md
- docs/quickstart/src/site/pages/thredds/ThreddsConfigRef.md
- docs/quickstart/src/site/pages/thredds/WmsRef.md
- docs/userguide/src/site/_data/sidebars/user_sidebar.yml
- docs/userguide/src/site/pages/thredds/ThreddsConfigRef.md
- docs/userguide/src/site/pages/thredds/WmsConfig.md
Most of the doc changes are related to WMS (see Unidata/tds#546), but this also syncs the threddsConfig.xml reference docs (including picking up the addition of the WMS palette conversion tool by @billyz313 from Unidata/tds#346).
> Documentation Update

- .github/CODEOWNERS
- .github/workflows/deps.yml
- .github/workflows/docs.yml
- .github/workflows/style.yml
GitHub is closing down actions/cache v1 and v2, and this PR bumps us to the latest (v4). This also bumps actions/setup-java to the latest version (v4). Additionally, update the CODEOWNERS file.
> github changes

- tds/src/integrationTests/java/thredds/server/wms/TestWmsServer.java
- tds/src/main/java/thredds/server/wms/ThreddsWmsServlet.java
Use "default" for the STYLES parameter of GetMap requests when the parameter is missing or empty. If not set, `default-<type>/default` (e.g. `default-scalar/default`) is used by edal-java, which does not take into account defaults set in wmsConfig.xml.
Fixes Unidata/tds#552
> BUG: set default styles parameter in GetMap requests 

- tds-ui/build.gradle
Replace the use of the gradle application plugin to run toolsUI and create gradle tasks to run both toolsUI and the TdsMonitor.
> Add gradle task to run TdsMonitor

- build.gradle
- docs/.gitignore
- docs/README.md
- docs/adminguide/src/site/pages/thredds/WmsConfig.md
- docs/build.gradle
- docs/userguide/src/site/pages/thredds/WmsConfig.md
- gradle/any/shared-mvn-coords.gradle
- project-files/jenkins/pipelines/docs
Migrate from jruby-based jekyll build to docker-based build. Configure a jenkins pipeline for doc build
> Build docs using docker

- LICENSE
- dap4/d4servlet/src/main/java/dap4/servlet/DapDSR.java
- tds/src/integrationTests/java/thredds/server/cdmr/TestCdmRemoteCompareHeadersP.java
- tds/src/main/java/thredds/servlet/restrict/TomcatAuthorizer.java
- tds/src/main/webapp/WEB-INF/applicationContext.xml
Use incoming request to determine the dap4 and tomcat authentication URL scheme (allowing an override for the latter). Also, fix an integration test such that it does not try to read a README file as a GRIB2 file, and update year in license.
> URL Scheme fixes

- tds-platform/build.gradle
- tds/src/main/webapp/WEB-INF/classes/log4j2.xml
Upgrade log4j and remove immediateFlush = false from threddsServlet log appender configuration.
> Upgrade log4j2 and TDS logging config

- tds/src/main/java/thredds/server/config/TdsInit.java
* make sure we can use the netCDF-C library defined in threddsConfig.xml by upgrading APIs used and order they are called
* If using netCDF-C for reading (testing only!), make sure the NetcdfFiles API registers the IOSP for reading.
Addresses Unidata/tds#607
> Fix issues with netCDF-C library defined in threddsConfig.xml

- gradle/any/shared-mvn-coords.gradle
- tds-platform/build.gradle
- tds/build.gradle
Upgrade netCDF-Java to 5.9.0 (release), and use latest edal-java and threddsIso snapshots (which now use netCDF-Java 5.9.0 release).
> Upgrade dependencies

- gradle/any/shared-mvn-coords.gradle
- gradle/root/dependency-check.gradle
- project-files/owasp-dependency-check/dependency-check-suppression.xml
- tds-platform/build.gradle
* cleanup dependency check suppression
* skip checking test-only package
* bump dependency check plugin, use NVD API key, if set
* bump quartz to v2.5.0
> Cleanup dependency check infrastructure

- tdcommon/build.gradle
- tdcommon/src/main/java/thredds/server/catalog/DatasetScan.java
- tdcommon/src/main/java/thredds/util/MFileUtils.java
- tds/src/integrationTests/java/thredds/server/catalog/TestTdsDatasetScan.java
- tds/src/integrationTests/java/thredds/tds/TestZarr.java
- tds/src/main/java/thredds/servlet/ServletUtil.java
- tds/src/test/content/thredds/tds-zarr.xml
Expose Zarr "directory" dataset as both a catalogRef and a direct access dataset for datasetScan generated catalogs. Fixes Unidata/tds#619
> Extend datasetScan to handle Zarr
