Unidata/tds

opendap/build.gradle
opendap/dtswar/build.gradle

stop publishing an empty opendap artifact :-/
my bad...

cleanup opendap build

---

gradle/any/dependencies.gradle

update jackson and spring security dependencies

---

docs/src/private/internal/release.md
gradle/any/dependencies.gradle

Release prep

---

tds/src/main/java/thredds/featurecollection/InvDatasetFcFmrc.java

Two main issues:
* All catalogs were getting Forecast Model Run datasets added to them
* Catalog for Constant Forecast Date datasets was using `makeOffsetDatasets` instead of `makeForecastDatasets` to add datasets

Fix FMRC catalog generation

---

tds/src/test/java/thredds/servlet/StaticViewerTest.java
travis/script.sh

Keeps TDS compiling after Unidata/netcdf-java#55

Remove unneeded catch

---

dap4/d4tests/src/test/java/dap4/test/TestNc4Iosp.java
it/src/freshInstallTest/groovy/thredds/tds/FreshTdsInstallSpec.groovy
it/src/test/java/thredds/TestOnLocalServer.java
it/src/test/java/thredds/server/services/TestAdminDebug.java
it/src/test/java/thredds/tds/TestRestrictDataset.java
it/src/test/java/ucar/nc2/util/net/TestSSH.java
it/src/test/java/ucar/nc2/util/net/TestTomcatAuth.java
tdm/src/main/java/thredds/tdm/Tdm.java

See Unidata/netcdf-java#117 for changes made to
httpservices.

Update authentication code to work with latest httpservices

---

docs/src/public/userguide/pages/tds_tutorial/getting_started/InstallJavaTomcat.md
docs/src/public/userguide/pages/tds_tutorial/getting_started/TomcatManagerApp.md

Updates to TDS docs:
- Changed flavor of jdk from oracle to openjdk
- Added additional step of creating a context file for the manager app in $TOMCAT_HOME/conf/Catalina/localhost

Docs update

---

docs/src/public/userguide/pages/tds_tutorial/getting_started/TomcatManagerApp.md

fixed typo in MD syntax

---

tds/src/main/java/thredds/server/ncss/controller/NcssGridController.java
tds/src/main/webapp/WEB-INF/templates/ncssFragments.html
tds/src/main/webapp/WEB-INF/templates/ncssGrid.html
tds/src/main/webapp/js/ncss/ncssApp.js

Revert "Wrf project"

---

tds/src/main/java/thredds/server/radarServer2/StationList.java

Will fix compile failures from Bearing api change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/53)

fix minor API change in Bearing

---

gradle/any/dependencies.gradle
it/src/test/java/thredds/server/opendap/TestS3Dap2.java
tds/build.gradle
tds/src/main/java/thredds/core/DatasetManager.java
tds/src/main/java/thredds/core/TdsRequestedDataset.java
tds/src/main/java/thredds/featurecollection/InvDatasetFeatureCollection.java
tds/src/main/java/thredds/monitor/NetcdfFileCacheMonitorImpl.java
tds/src/main/java/thredds/server/admin/DebugCommands.java
tds/src/main/java/thredds/server/config/TdsInit.java
tds/src/main/java/thredds/server/reify/DownloadController.java
tds/src/main/java/thredds/server/wfs/WFSController.java
tds/src/test/content/thredds/catalog.xml
tds/src/test/content/thredds/tds-s3.xml
tds/src/test/java/thredds/server/ncss/view/dsg/DsgSubsetWriterTest.java
tds/src/test/java/thredds/server/opendap/TestCEEvaluator.java
testUtil/src/main/java/ucar/unidata/util/test/TestDir.java
testUtil/src/main/java/ucar/unidata/util/test/UnitTestCommon.java

* Update to netCDF-Java 5.4.0-SNAPSHOT
* Move to using `NetcdfFiles`, `NetcdfDatasets`
* Add simple S3 related test

Update netCDF-Java, add base S3 capibilities

---

gradle/any/dependencies.gradle
tdcommon/src/main/java/thredds/server/catalog/DatasetScan.java
tds/src/main/java/thredds/core/ConfigCatalogHtmlWriter.java
tds/src/main/java/thredds/server/catalogservice/CatalogViewContextParser.java
tds/src/main/java/thredds/server/catalogservice/RemoteCatalogServiceController.java
tds/src/main/java/thredds/server/config/TdsUpdateConfigBean.java
tds/src/main/java/thredds/server/radarServer2/RadarServerController.java
tds/src/main/java/thredds/server/wfs/WFSController.java
tds/src/main/webapp/WEB-INF/templates/ncssFragments.html
tds/src/test/content/thredds/rootCatalog2.xml
tds/src/test/content/thredds/threddsConfig.xml

Various fixes including:
* removing hardcoded "/thredds/" strings and grabbing the context from tdsContext.
* updating a few dependencies
* updating a few urls

Various fixes

---

docs/src/private/internal/CoordinateSystemsNeeded.adoc
docs/src/private/internal/release.md
docs/src/private/website/netcdf-java/metadata/DataDiscoveryAttConvention.adoc
docs/src/private/website/netcdf-java/ncml/index.adoc
docs/src/private/website/netcdf-java/reference/ToolsUI/ToolsUI.adoc
docs/src/private/website/tds/catalog/InvCatalogSpec.adoc
docs/src/private/website/tds/reference/ThreddsConfigXMLFile.adoc
docs/src/public/userguide/pages/tds_tutorial/getting_started/DeployingTheTds.md
docs/src/public/userguide/pages/tds_tutorial/production/InstallationChecklist.md
docs/src/public/userguide/pages/tds_tutorial/tds_configuration/AddingOgcIsoServices.md
docs/src/public/userguide/pages/thredds/TdmRef.md
docs/src/public/userguide/pages/thredds/ThreddsConfigRef.md
it/src/test/data/thredds/catalog/InvCatalog-1.0.xml
opendap/README.txt
opendap/server/src/main/java/opendap/servlet/www/jscriptCore.java
opendap/server/src/main/java/opendap/servlet/www/jscriptCore.tmpl

- removed unidata downloads site index.jsp references
- removed references to my.unidata domain
- removed references to old package convention in unidata urls

First pass at correcting know issues with URLs in links and references.

---

tdcommon/src/main/java/thredds/server/catalog/builder/CatalogScanBuilder.java
tdcommon/src/main/java/thredds/server/catalog/builder/ConfigCatalogBuilder.java
tdcommon/src/main/java/thredds/server/catalog/builder/DatasetScanBuilder.java
tdcommon/src/main/java/thredds/server/catalog/builder/FeatureCollectionRefBuilder.java
tds/src/main/java/thredds/core/ConfigCatalogInitialization.java

...otherwise, fallback to `/thredds/`.

have catalog builders use servlet context if provided

---

gradle/any/dependencies.gradle
it/src/test/java/opendap/test/TestGrid1.java
it/src/test/java/opendap/test/TestGrid2.java
it/src/test/java/thredds/client/catalog/TestResolve.java
it/src/test/java/thredds/server/cdmr/TestCdmRemoteCompareDataP.java
it/src/test/java/thredds/server/cdmr/TestCdmRemoteCompareHeadersP.java
it/src/test/java/thredds/server/cdmr/TestCdmRemoteMisc.java
it/src/test/java/thredds/server/cdmr/TestCdmrTiming.java
it/src/test/java/thredds/server/fileserver/TestHTTP.java
it/src/test/java/thredds/server/fileserver/TestHttpOpen.java
it/src/test/java/thredds/server/opendap/TestDODScompareWithFiles.java
it/src/test/java/thredds/server/opendap/TestOpendapMisc.java
it/src/test/java/thredds/server/opendap/TestOutstandingIssues.java
it/src/test/java/thredds/server/opendap/TestTdsDodsServer.java
it/src/test/java/thredds/server/wcs/TestWcsServer.java
it/src/test/java/thredds/tds/TestTdsNcml.java
it/src/test/java/ucar/nc2/TestByteRange.java
it/src/test/java/ucar/nc2/dt/grid/TestTime2D.java
tdm/src/main/java/thredds/tdm/GCpass1.java
tdm/src/main/java/thredds/tdm/GCsummary.java
tdm/src/main/java/thredds/tdm/Tdm.java
tds/src/main/java/thredds/server/wcs/v1_0_0_1/WcsCoverage.java
tds/src/test/java/thredds/server/ncss/controller/grid/DefaultDateRangeTest.java
tds/src/test/java/thredds/server/ncss/controller/grid/GridCoverageSubsettingTest.java
tds/src/test/java/thredds/servlet/DatasetSourceExample.java
tds/src/test/java/thredds/util/xml/XmlUtil.java

Other misc deprecation fixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/85)

Change tests to use new code where possible.

---

dap4/d4tests/src/test/java/dap4/test/TestNc4Iosp.java
it/src/test/java/thredds/server/catalog/TestServiceDefaults.java
it/src/test/java/thredds/server/catalog/TestTdsGrib.java
it/src/test/java/thredds/server/cdmrf/TestGribFmrcRegularTime.java
it/src/test/java/thredds/tds/TestTdsNcml.java
it/src/test/java/ucar/nc2/util/net/TestTomcatAuth.java
tds/src/main/java/thredds/server/catalogservice/RemoteCatalogServiceController.java
tds/src/main/java/thredds/server/ncss/controller/NcssPointController.java
tds/src/main/webapp/WEB-INF/tdsGlobalConfig.xml
tds/src/main/webapp/WEB-INF/templates/pointFragments.html
tds/src/test/java/thredds/server/catalogservice/RemoteCatalogControllerTest.java
tds/src/test/java/thredds/server/ncss/controller/point/TestStationFcOpenFiles.java
testUtil/src/main/java/ucar/unidata/util/test/Diff.java
testUtil/src/main/java/ucar/unidata/util/test/UnitTestCommon.java

This PR will get us down to seven failures on Jenkins. Two dap4, and five related to vlen and structures as seen through cdmremote.

Many fixes for Jenkins

---

.github/workflows/tds.yml
tds/src/main/java/thredds/server/ncss/controller/NcssGridController.java
tds/src/main/java/thredds/server/ncss/view/dsg/DsgSubsetWriterFactory.java
tds/src/main/java/thredds/server/ncss/view/dsg/point/AbstractPointSubsetWriter.java
tds/src/main/java/thredds/server/ncss/view/dsg/point/PointSubsetWriterNetcdf.java
tds/src/main/java/thredds/server/reify/DownloadController.java
tds/src/main/java/thredds/server/wcs/v1_0_0_1/WcsCoverage.java
tds/src/main/java/thredds/util/TdsPathUtils.java

Changes to NetcdfFormatWriter.

---

it/src/test/java/thredds/tds/TestTdsNcml.java
tds/src/main/java/thredds/server/cdmremote/CdmRemoteController.java
tds/src/test/java/thredds/server/cdmremote/CdmrControllerTest.java
tds/src/test/java/thredds/util/xml/NcmlParserUtil.java

Update related to Unidata/netcdf-java#342

Minor update for netCDF-Java change

---

tds/src/main/java/thredds/server/ncss/controller/NcssGridController.java
tds/src/main/java/thredds/server/wcs/v1_0_0_1/WcsCoverage.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/100)

NetcdfFormatWriter.Result was moved.

---

.github/workflows/tds.yml
dap4/d4ts/build.gradle
gradle/any/gretty.gradle
opendap/dtswar/build.gradle
tds/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/111)

Test against tomcat 8.5.x and 9.x

---

.github/workflows/docs.yml
.github/workflows/tds.yml
gradle/root/sonarqube.gradle
tds-platform/build.gradle

Applicable portions of PR Unidata/netcdf-java#521
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/118)

Build fixes

---

tds/src/main/webapp/WEB-INF/altContent/startup/jupyter_notebooks/default_viewer.ipynb

- reformat notebook metadata
- add missing ')'
- missing import statement
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/120)

couple things that got left out of the notebook redesign PR

---

.gitignore
gradle/root/dependency-check.gradle
project-files/owasp-dependency-check/dependency-check-suppression.xml
tdm/build.gradle
tdm/src/main/resources/resources/application-config.xml
tds-platform/build.gradle
tds/src/main/java/thredds/core/DatasetManager.java
tds/src/main/java/thredds/server/ncss/controller/NcssGridController.java
tds/src/main/webapp/WEB-INF/applicationContext.xml
tds/src/test/content/thredds/tds-s3.xml

Enable catalog based NcML aggregations against object store resources. Also try to filter out bad values from the computed bounding box that is used to display a boundary on the map of the NCSS page (and provide a default so that the page still loads). This needs more work.
Also includes a few other dependency related tasks:
* bump version of spring and spring security
* update dependency check suppression file to ignore false positives
* make sure to fail the build if any vulnerable dependencies are found
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/121)

Catalog based NcML aggregations against object store resources

---

gradle/any/javadoc.gradle
testUtil/src/main/java/ucar/unidata/util/test/Diff.java
testUtil/src/main/java/ucar/unidata/util/test/SysStreamLogger.java
testUtil/src/main/java/ucar/unidata/util/test/TestDir.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/131)

Make javadoc happy with java 11.

---

tds/src/integrationTests/java/thredds/server/radar/TestRadarServer.java
tds/src/main/java/thredds/server/radarServer2/RadarServerController.java
tds/src/test/content/thredds/radar/CS039_L2_stations.xml
tds/src/test/content/thredds/radar/CS039_stations.xml
tds/src/test/content/thredds/radar/RadarNexradStations.xml
tds/src/test/content/thredds/radar/RadarTerminalStations.xml
tds/src/test/content/thredds/radar/nccsRadarlevel2.xslt
tds/src/test/content/thredds/radar/radarCollections.xml
tds/src/test/content/thredds/threddsConfig.xml

In this PR, we:
1. enhance the `RadarServer` test to fail when the service is partially initialized. We were getting a `200` response from the partially initialized service, but no content. Boo. Now we check for valid content.
1. fix the initialization issue in `RadarServerController`.
1. Update the `RadarServer` configs to be in-line with what we have in the [TdsConfig](https://github.com/Unidata/TdsConfig/tree/master/idd/radar) project.
Now the `RadarServer` works and the test pass for realzies (or at least _more_ for realzies).
_<ForRealziesIntensifies.gif>_
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/138)

Fix the TDS RadarServer

---

tds-test-utils/src/main/java/thredds/test/util/TdsTestDir.java
tds-test-utils/src/main/java/thredds/test/util/TestOnLocalServer.java
tds/src/integrationTests/java/thredds/server/cdmr/TestCdmRemoteCompareHeadersP.java
tds/src/integrationTests/java/thredds/server/ncss/NcssGridIntegrationTest.java
tds/src/integrationTests/java/thredds/server/ncss/TestGridAsPointP.java
tds/src/integrationTests/java/thredds/server/services/ConsistentDatesTest.java
tds/src/integrationTests/java/thredds/server/wcs/TestWcsServer.java
tds/src/integrationTests/java/thredds/tds/TestRestrictDataset.java
tds/src/integrationTests/java/thredds/tds/TestRestrictNoAuth.java
tds/src/integrationTests/java/thredds/tds/TestTdsNcml.java
tds/src/main/java/thredds/core/DatasetManager.java
tds/src/main/java/thredds/featurecollection/InvDatasetFcFmrc.java
tds/src/test/java/thredds/server/ncss/controller/grid/AllVariablesSubsettingTest.java
tds/src/test/java/thredds/server/ncss/controller/grid/FmrcHorizSubsettingTest.java
tds/src/test/java/thredds/server/ncss/controller/grid/SpatialSubsettingTest.java
tds/src/test/java/thredds/server/ncss/controller/grid/TemporalSpaceSubsettingTest.java
tds/src/test/java/thredds/server/ncss/controller/grid/VariableSpaceSubsettingTest.java
tds/src/test/java/thredds/server/ncss/controller/grid/VerticalStrideSubsettingTest.java
tds/src/test/java/thredds/server/ncss/controller/point/TestStationFcOpenFiles.java
tds/src/test/java/thredds/server/ncss/view/dsg/DsgSubsetWriterTest.java
tds/src/test/java/thredds/server/opendap/TestCEEvaluator.java

This PR brings us down to 8 test failures on Jenkins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/141)

Fix more Jenkins tests

---

gradle/root/publishing.gradle
tdm/build.gradle
tds/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/145)

Publish tds war and tdm jar to downloads repository

---

build.gradle
docs/adminguide/src/site/_config.yml
docs/adminguide/src/site/pages/installation_upgrade/ReleaseNotes.md
docs/adminguide/src/site/pages/installation_upgrade/SystemRequirements.md
docs/adminguide/src/site/pages/support_troubleshooting/Faqs.md
docs/adminguide/src/site/pages/workshops/2018UnidataTrainingWorkshop.md
docs/devguide/src/site/_config.yml
docs/devguide/src/site/_data/sidebars/dev_sidebar.yml
docs/devguide/src/site/pages/tds_tutorial/faq/faq.md
docs/devguide/src/site/pages/tds_tutorial/getting_started/InstallJavaTomcat.md
docs/devguide/src/site/pages/workshops/2018UnidataTrainingWorkshop.md
docs/quickstart/src/site/_config.yml
docs/quickstart/src/site/_data/sidebars/quickstart_sidebar.yml
docs/quickstart/src/site/pages/tds_tutorial/getting_started/InstallJavaTomcat.md
docs/quickstart/src/site/pages/tds_tutorial/production/Upgrade.md
docs/quickstart/src/site/pages/workshops/2018UnidataTrainingWorkshop.md
docs/userguide/src/site/_config.yml
docs/userguide/src/site/_data/sidebars/user_sidebar.yml
docs/userguide/src/site/pages/tds_tutorial/faq/faq.md
docs/userguide/src/site/pages/tds_tutorial/getting_started/InstallJavaTomcat.md
docs/userguide/src/site/pages/tds_tutorial/production/Upgrade.md
docs/userguide/src/site/pages/workshops/2018UnidataTrainingWorkshop.md
gradle/root/publishing.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/149)

Release 5.0.0 beta9

---

.github/workflows/tds.yml
docs/build.gradle
gradle.properties
gradle/root/publishing.gradle
tds/src/main/java/thredds/core/ConfigCatalogHtmlWriter.java
tds/src/main/java/thredds/server/admin/HtmlWriting.java
tds/src/main/webapp/WEB-INF/classes/thredds/server/tds.properties
tds/src/main/webapp/WEB-INF/jsp/simpleFooter.jsp
tds/src/main/webapp/WEB-INF/jsp/thredds/server/catalog/catalog.jsp
tds/src/main/webapp/WEB-INF/jsp/thredds/server/serverinfo/serverInfo_html.jsp
tds/src/main/webapp/WEB-INF/jsp/thredds/server/serverinfo/serverInfo_xml.jsp
tds/src/main/webapp/WEB-INF/jsp/thredds/server/serverinfo/serverVersion_txt.jsp
tds/src/main/webapp/WEB-INF/jsp/webappFooter.jsp
tds/src/main/webapp/WEB-INF/templates/commonFragments.html

* Fix download and doc publishing:
* Publish docs under version/ and not project/version
* Increase heap space to account for memory needed for publishDownoads
* Remove server version info from catalog and serverInfo service.
* Upgrade to thredds-test-action@v2 and add zulu 14 to test matrix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/150)

Miscellaneous tweaks / fixes

---

docs/adminguide/src/site/pages/installation_upgrade/ReleaseNotes.md
tds/src/main/webapp/WEB-INF/altContent/startup/wmsConfig.xml
tds/src/test/content/thredds/wmsConfig.xml
tds/src/test/java/thredds/server/wms/config/WmsDetailedConfigTest.java

Closes Unidata/tds#151
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/152)

Update wmsConfig.xml and Document changes to color palette names

---

docs/shared/src/site/_data/topnav.yml.golden

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/155)

Fix topnav menu links.

---

docs/shared/src/site/_data/topnav.yml.golden

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/162)

removed link to admin guide

---

tds-platform/build.gradle

Spring upgrade to address CVE-2021-22096
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/175)

spring framework upgrade

---

docs/adminguide/src/site/_config.yml
docs/adminguide/src/site/_data/sidebars/admin_sidebar.yml
docs/devguide/src/site/_config.yml
docs/devguide/src/site/_data/sidebars/dev_sidebar.yml
docs/quickstart/src/site/_config.yml
docs/quickstart/src/site/_data/sidebars/quickstart_sidebar.yml
docs/userguide/src/site/_config.yml
docs/userguide/src/site/_data/sidebars/user_sidebar.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/178)

update docsets to working version, 5.2

---

tds-platform/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/180)

update threddsIso version

---

gradle/any/shared-mvn-coords.gradle
tds-platform/build.gradle

Bump log4j to 2.16.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/181)

upgrade log4j to 2.16.0

---

project-files/owasp-dependency-check/dependency-check-suppression.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/182)

suppressing false positive owasp hit for h2-1.3.173.jar

---

tds-platform/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/186)

bump threddsISO to snapshot

---

tds-platform/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/187)

more log4j, forever log4j

---

tds/src/main/webapp/WEB-INF/classes/thredds/server/tds.properties

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/188)

fix link to tds docs, used by thymeleaf footer

---

gradle/any/shared-mvn-coords.gradle
tds-platform/build.gradle
tds/src/main/webapp/WEB-INF/applicationContext.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/191)

test PR: match netcdf-java and tds protobuf versions

---

project-files/owasp-dependency-check/dependency-check-suppression.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/192)

suppress false positive in owasp scan

---

tds/src/main/java/thredds/server/notebook/NotebookController.java

only allow the notebook service to return .py or .ipynb files from within the notebook folder in the content directory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/195)

security patch to notebook service

---

project-files/owasp-dependency-check/dependency-check-suppression.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/197)

suppress another h2 false positive CVE

---

tds/src/main/java/thredds/server/radarServer2/RadarServerController.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/198)

accommodate zpositive value in IDV stringbuilder code

---

docs/devguide/src/site/pages/thredds/TdsServices.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/199)

document catalog service path, which requires /catalog/ in v5.x

---

docs/adminguide/src/site/pages/thredds/TdsServices.md
docs/quickstart/src/site/pages/thredds/TdsServices.md
docs/userguide/src/site/pages/thredds/TdsServices.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/200)

add /catalog/ to service path in all docsets

---

tds/src/main/java/thredds/server/ncss/validation/TimeParamsValidator.java
tds/src/main/webapp/WEB-INF/templates/ncssGrid.html
tds/src/main/webapp/WEB-INF/templates/ncssGridAsPoint.html
tds/src/main/webapp/WEB-INF/templates/ncssPoint.html
tds/src/main/webapp/WEB-INF/templates/ncssStation.html
tds/src/main/webapp/js/ncss/ncssApp.js

remove client side validation
fill in query params as values are added
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/202)

fix ncss query time validation

---

project-files/owasp-dependency-check/dependency-check-suppression.xml

Suppress CWE-94 for h2 (not in TDS codebase)
OWASP passing on Jenkins now
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/203)

suppress h2 OWASP

---

tds/src/test/java/thredds/server/catalog/TestDatasetScan.java

Minor cleanups to one test class
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/204)

Cleanup tests

---

tds-test-utils/src/main/java/thredds/test/util/TestOnLocalServer.java
tds/src/integrationTests/java/thredds/server/fileserver/TestFileServer.java
tds/src/integrationTests/java/thredds/server/ncss/NcssGridIntegrationTest.java
tds/src/integrationTests/java/thredds/server/opendap/TestTdsDodsServer.java
tds/src/integrationTests/java/thredds/server/wcs/TestWcsServer.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/206)

Fix some failing tests

---

project-files/owasp-dependency-check/dependency-check-suppression.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/210)

suppress wire-ios cve

---

tds-platform/build.gradle

- address CVE-2022-22965
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/214)

upgrade spring bom

---

tds-platform/build.gradle
tds-testing-platform/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/219)

upgrade spring to 5.3.19

---

.github/helperScripts/dispatch.sh
.github/workflows/update-docker.yml

Manual workflow dispatch with input through Github's UI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/223)

Workflow dispatch to update image on unidata/thredds-docker

---

tds/src/integrationTests/java/thredds/tds/TestTdsNestedAggregation.java
tds/src/test/content/thredds/catalog.xml
tds/src/test/content/thredds/catalogNestedAgg.xml

Test for nested aggregation, which reproduces #225 
(Bug fixed in https://github.com/Unidata/netcdf-java/pull/1019, so this test should pass when that is merged)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/226)

[5.x] Add test for nested aggregation

---

tds/src/main/webapp/WEB-INF/altContent/startup/threddsConfig.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/224)

threddsConfig xml error in commented xml

---

docs/adminguide/src/site/pages/thredds/ThreddsConfigRef.md
docs/quickstart/src/site/pages/thredds/ThreddsConfigRef.md
docs/userguide/src/site/pages/thredds/ThreddsConfigRef.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/233)

add info on feature collection cache to various docsets

---

project-files/owasp-dependency-check/dependency-check-suppression.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/237)

suppress false positive CVE for commons-io

---

build.gradle
gradle/any/shared-mvn-coords.gradle
tds-platform/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/239)

Release 5.4

---

tds/src/main/java/thredds/server/config/TdsContext.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/243)

TdsContext: Correct path in error message for notebooks directory

---

project-files/owasp-dependency-check/dependency-check-suppression.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/247)

suppress wire-ios CVE warning

---

tds/src/main/java/thredds/server/catalogservice/CatalogViewContextParser.java
tds/src/main/webapp/WEB-INF/templates/datasetFragments.html

- fix link to top-level catalog
- remove "back to catalog" link from dataset page
- light refactoring and clean up of dataset context
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/248)

fix link to top-level catalog and remove from dataset page

---

tds/src/main/java/thredds/server/catalogservice/CatalogViewContextParser.java
tds/src/main/webapp/WEB-INF/templates/dataset.html
tds/src/main/webapp/WEB-INF/templates/datasetFragments.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/249)

remove fragment from dataset page

---

tds/src/main/java/thredds/server/catalogservice/CatalogViewContextParser.java
tds/src/main/webapp/WEB-INF/templates/dataset.html

- fix return to catalog link (for real this time)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/253)

Catalog links

---

docs/adminguide/src/site/pages/thredds/NcssGrid.md
docs/adminguide/src/site/pages/thredds/NcssRef.md
docs/devguide/src/site/_data/sidebars/dev_sidebar.yml
docs/devguide/src/site/pages/thredds/NcssGrid.md
docs/devguide/src/site/pages/thredds/NcssRef.md
docs/quickstart/src/site/_data/sidebars/quickstart_sidebar.yml
docs/quickstart/src/site/pages/thredds/NcssGrid.md
docs/quickstart/src/site/pages/thredds/NcssRef.md
docs/userguide/src/site/_data/sidebars/user_sidebar.yml
docs/userguide/src/site/pages/thredds/NcssGrid.md
docs/userguide/src/site/pages/thredds/NcssRef.md

- Fix bad link in documentation
- Fix capitalization of "grid"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/256)

Fix bad link in documentation

---

tds/src/main/webapp/WEB-INF/altContent/startup/wmsConfig.xml
tds/src/test/content/thredds/wmsConfig.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/257)

update schema reference in startup and test wmsConfig

---

docs/adminguide/src/site/pages/thredds/NcssRef.md
docs/devguide/src/site/pages/thredds/NcssRef.md
docs/quickstart/src/site/pages/thredds/NcssRef.md
docs/userguide/src/site/pages/thredds/NcssRef.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/258)

Fix documentation links

---

docs/adminguide/src/site/pages/tds_tutorial/feature_collections/FmrcTutorial.md
docs/adminguide/src/site/pages/tds_tutorial/tds_configuration/AddingNcss.md
docs/devguide/src/site/pages/tds_tutorial/feature_collections/FmrcTutorial.md
docs/devguide/src/site/pages/tds_tutorial/tds_configuration/AddingNcss.md
docs/quickstart/src/site/pages/tds_tutorial/feature_collections/FmrcTutorial.md
docs/quickstart/src/site/pages/tds_tutorial/tds_configuration/AddingNcss.md
docs/userguide/src/site/pages/tds_tutorial/feature_collections/FmrcTutorial.md
docs/userguide/src/site/pages/tds_tutorial/tds_configuration/AddingNcss.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/266)

Fix typos in the documentation

---

tdcommon/src/main/java/thredds/server/catalog/CatalogScan.java
tdcommon/src/main/java/thredds/server/catalog/DatasetScan.java

Update DatasetScan and CatalogScan error messages to use URL path instead of file path.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/273)

Update error message

---

tds/src/main/java/thredds/server/ncss/view/dsg/DsgSubsetWriterFactory.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/276)

clarigy error message for any_point ncss request

---

tds/src/main/java/thredds/servlet/ServletUtil.java

Use URL path instead of file path in error message
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/278)

Improve error message

---

tds/src/integrationTests/java/thredds/server/opendap/OpendapByteTest.java
tds/src/main/java/thredds/server/opendap/NcDAS.java

Addresses the TDS side of Unidata/tds#277
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/279)

Include the _Unsigned attribute for all DAP2 byte variables

---

docs/userguide/src/site/pages/tds_tutorial/faq/faq.md
tds/src/main/webapp/WEB-INF/classes/log4j2.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/299)

Improve comment and fix typo

---

tds/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/304)

Remove aws sts now that it is pulled in with cdm-s3

---

tdcommon/src/main/java/thredds/server/catalog/DataRoot.java
tdcommon/src/main/java/thredds/server/catalog/DataRootPathMatcher.java
tds/src/test/java/thredds/servlet/TestPathMatcher.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/313)

do not match partial dataRoots

---

tds-platform/build.gradle
tds-testing-platform/build.gradle

upgrade spring boms
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/314)

CVE-2022-31692

---

tds/src/main/java/thredds/server/notebook/NotebookMetadata.java
tds/src/test/data/testNotebookMetadata.json
tds/src/test/java/thredds/server/notebook/TestNotebookService.java

- relax requirement for matching a notebook to a dataset in a catalog
- add tests for notebook registration
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/326)

notebook registration

---

tds/src/main/java/thredds/server/notebook/NotebookMetadata.java

- add null checks to notebook matching logic
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/330)

safety rails

---

tds/src/integrationTests/java/thredds/tds/TestTdsNcml.java

Use google truth asserts in TestTdsNcml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidata/tds/334)

Use google truth asserts in TestTdsNcml

---

docs/userguide/src/site/pages/tds_tutorial/production/PerformanceTips.md

Fix JDK version by linking to system requirements and fix outdated year 200x reference
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/341)

Fix java/tomcat version in docs

---

tds/src/test/java/thredds/server/ncss/controller/grid/GridDatasetControllerTest.java

Test for issue: https://github.com/Unidata/tds/issues/349
Depends on fix in netcdf-java: https://github.com/Unidata/netcdf-java/pull/1160
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/351)

Add test for nullptr exception in NCSS dataset description

---

docs/userguide/src/site/pages/tds_tutorial/faq/faq.md
docs/userguide/src/site/pages/thredds/ThreddsConfigRef.md

Also fix minor typo that resulted in bad rendering for one item in the FAQ.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/357)

Add pointers to WMS Magic Palette Converter

---

docs/userguide/src/site/pages/thredds/DatasetScanRef.md
tdcommon/build.gradle
tdcommon/src/main/java/thredds/server/catalog/DataRoot.java
tdcommon/src/main/java/thredds/server/catalog/DatasetScan.java
tdcommon/src/main/java/thredds/server/catalog/builder/DatasetScanConfigBuilder.java
tdcommon/src/test/java/thredds/server/catalog/TestDataRoot.java
tds/src/integrationTests/java/thredds/server/fileserver/TestFileServer.java
tds/src/test/content/thredds/tds-s3.xml
tds/src/test/java/thredds/server/catalog/TestDatasetScan.java
tds/src/test/java/thredds/server/catalog/TestDatasetScanS3.java
tds/src/test/resources/thredds/server/catalog/TestDatasetScan.xml
tds/src/test/resources/thredds/server/catalog/TestDatasetScanS3.xml

Resolves: https://github.com/Unidata/tds/issues/358
- Fix dataRoots to work for cdms3 URIs and test this (had to add gradle dependencies for testing and for s3 so that s3 file provider could be used)
- Refactor DatasetScans to use `MControllers` which work for local and s3 files. 
- Add datasetScan tests for S3 and improve existing tests
- Add few sentences to the datasetScan documentation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/359)

S3 dataset scan

---

tdcommon/src/main/java/thredds/server/catalog/ConfigCatalogCache.java
tds/src/main/java/thredds/server/TdsErrorHandling.java

Improve error messages for a catalog that cannot be read because its a directory or its invalid
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/364)

Improve invalid catalog error messages

---

tds/src/integrationTests/java/thredds/server/wms/TestUpdateWmsServer.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/375)

ignore other tests

---

dap4/build.gradle
dap4/d4servlet/build.gradle
dap4/d4servlet/src/main/java/dap4/servlet/DSPFactory.java
dap4/d4tests/build.gradle
dap4/d4ts/build.gradle
settings.gradle
tds-platform/build.gradle
tds/build.gradle
tds/src/integrationTests/java/ucar/nc2/util/net/TestFormBuilder.java
tds/src/main/java/thredds/server/dap4/Dap4Controller.java
tds/src/main/java/thredds/server/dap4/ThreddsDSP.java

see https://github.com/Unidata/netcdf-java/pull/1152
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/379)

update gradle to reference new combined dap4 module in ncj

---

tds/src/main/java/thredds/core/ConfigCatalogHtmlWriter.java
tds/src/main/java/thredds/server/admin/HtmlWriting.java
tds/src/main/webapp/WEB-INF/templates/catalog.html

I think this set of changes should work to fix [Unidata/tds#](https://github.com/Unidata/tds/issues/387)
I've tested that the changes to the `Catalog.html` file work if hacked into the exploded webpp, but haven't yet tried to compile the source and deploy my own copy to test the changes in `HtmlWriting.java` and `ConfigCatalogHtmlWriter.java` files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/388)

Unidata/tds#387 Switch from Google's Universal Analytics to Google tag

---

tds/src/main/java/thredds/server/exception/RequestTooLargeException.java
tds/src/main/java/thredds/server/ncss/controller/NcssGridController.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/395)

throw correct error if result is not written

---

tds/src/main/java/thredds/server/catalogservice/CatalogViewContextParser.java
tds/src/main/java/thredds/server/views/TdsExtensibleTemplateResolver.java

Fixes part of #353  where installUrl is not correct
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/397)

fix installUrl

---

tds-platform/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/400)

Upgrade spring security

---

tds-platform/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/408)

upgrade thymeleaf

---

tds/src/integrationTests/java/opendap/test/TestNcmlWithOpendap.java
tds/src/test/content/thredds/catalog.xml

Integration tests for fix in https://github.com/Unidata/netcdf-java/pull/1222. Won't pass until that PR is merged.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/404)

Add integration tests for ncml with enhancements

---

tds/src/integrationTests/java/thredds/server/ncss/NcssGridIntegrationTest.java
tds/src/test/java/thredds/server/ncss/controller/grid/GridDatasetControllerTest.java
tds/src/test/java/thredds/server/ncss/controller/grid/SpatialSubsettingTest.java
tds/src/test/java/thredds/server/ncss/controller/grid/TemporalSpaceSubsettingTest.java
tds/src/test/java/thredds/server/ncss/controller/grid/VariableSpaceSubsettingTest.java
tds/src/test/java/thredds/server/ncss/controller/point/TestStationFCController.java
tds/src/test/java/thredds/util/TestUtils.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/415)

refactor skip if nc4 is not present to static utility

---

docs/userguide/src/site/pages/tds_tutorial/metadata/IsoMetadataRef.md
docs/userguide/src/site/pages/tds_tutorial/tds_configuration/AddingOgcIsoServices.md

- update link for threddsIso, and remove broken link to 4.x docs
- update mentions of godiva2 to godiva3
- remove mentions of IDV and ToolsUI in the dataset viewers
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/416)

Update docs about iso services

---

project-files/owasp-dependency-check/dependency-check-suppression.xml
tds-platform/build.gradle

- bump spring security version
- suppress CVE that should not affect us and is anyways disputed (https://github.com/quartz-scheduler/quartz/issues/943)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/419)

Update spring security and suppress false positive CVE

---

tds-platform/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/423)

upgrade json lib

---

tds/src/integrationTests/java/thredds/server/services/TestEnhancements.java
tds/src/test/content/thredds/catalog.xml

tests fix for #282
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/431)

add test for applying enhancements in the TDS

---

tds/src/main/java/thredds/core/DatasetManager.java
tds/src/main/java/thredds/servlet/ServletUtil.java

Hide file paths for bad HttpServer Requests and don't disclose too much info for unsupported NCSS Point requests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/436)

Remove security vulnerabilities 

---

tds/src/test/java/thredds/server/ncss/controller/point/TestPointFCExceptions.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/437)

Update expected error message in test

---

tds/src/integrationTests/java/thredds/tds/TestS3Ncml.java
tds/src/test/java/thredds/server/ncss/view/dsg/DsgSubsetWriterTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/442)

ignore dsgsubsetwriter tests

---

opendap/server/src/main/java/opendap/servers/SubClause.java
opendap/server/src/main/java/opendap/servers/TopLevelClause.java
opendap/server/src/main/java/opendap/servers/parsers/CeParser.java
opendap/server/src/main/java/opendap/servlet/DummySink.java
tdcommon/src/main/java/thredds/server/catalog/DataRoot.java
tdcommon/src/main/java/thredds/util/ThreddsConfigReader.java
tds-test-utils/src/main/java/thredds/test/util/TdsUnitTestCommon.java
tds-ugrid/src/main/java/ucar/nc2/dt/UGridDatatype.java
tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/geom/LatLonPoint2D.java
tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/geom/LatLonRectangle2D.java
tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/geom/Point3D.java
tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/geom/Polygon2D.java
tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/geom/Vector3D.java
tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/rtree/IntProcedureEntriesList.java
tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/rtree/IntProcedureEntriesStack.java
tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/rtree/Node.java
tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/rtree/RTree.java
tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/utils/AsaMath.java
tds/src/main/java/thredds/server/ncss/validation/NcssGridRequestValidator.java
tds/src/main/java/thredds/server/opendap/NcSDArray.java
tds/src/main/java/thredds/server/opendap/NcSDCharArray.java
tds/src/main/java/thredds/server/opendap/NcSDGrid.java
tds/src/main/java/thredds/server/viewer/Viewer.java
tds/src/main/java/thredds/server/viewer/ViewerLinkProvider.java
tds/src/main/java/thredds/server/wfs/WFSExceptionWriter.java
tds/src/main/java/thredds/server/wms/config/WmsDetailedConfig.java
tds/src/main/java/thredds/servlet/filter/RequestPathFilter.java
tds/src/main/java/thredds/servlet/filter/RequestQueryFilter.java
tds/src/main/java/thredds/util/StringValidateEncodeUtils.java
tds/src/main/java/ucar/util/prefs/XMLStore.java

Fix various javadoc warnings related to certain special characters, incorrect `@param` arguments and broken `@see` links.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/446)

Fix javadoc warnings

---

tds/src/test/java/thredds/server/ncss/controller/grid/GridCoverageSubsettingTest.java

Update nearlyEquals tolerance in test (now an absolute tolerance instead of relative tolerance)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/453)

Update test nearlyEquals tolerance

---

tds/src/main/java/thredds/server/config/TdsInit.java

Add flag to RandomAccessFile cache to cleanup deleted files
Depends on https://github.com/Unidata/netcdf-java/pull/1304
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Unidata/tds/463)

Add flag to RandomAccessFile cache to cleanup deleted files

---

tds/src/main/java/thredds/server/config/TdsConfigMapper.java
tds/src/main/webapp/WEB-INF/classes/log4j2.xml

Make sure edal-java/WMS logs errors when loading custom styles

Improve logging

---

tds/src/main/java/thredds/core/DatasetManager.java

Use fix from https://github.com/Unidata/netcdf-java/pull/1317. Needs that fix to compile.

Fix performance issue that aggregation cache not used for coverages

---

project-files/owasp-dependency-check/dependency-check-suppression.xml
tds-platform/build.gradle

- Revert unneeded change from https://github.com/Unidata/tds/pull/479/
- Bump spring security version

Update spring security

---

docs/userguide/src/site/pages/thredds/ThreddsConfigRef.md

fix instructions for using your own logo

---

tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/geom/LatLonPolygon2D.java
tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/geom/Point3D.java
tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/geom/Polygon2D.java
tds/src/main/java/thredds/featurecollection/InvDatasetFcFmrc.java

Fix some minor issues flagged by Coverity static analysis

Coverity fixes

---

project-files/owasp-dependency-check/dependency-check-suppression.xml

Suppress three spurious and not applicable jfreechart CVEs. Suppress these for both the TDS war file (jfreechart dependency comes from edal-java) and tds-ui (tools UI).

Suppress CVEs

---

.github/workflows/tds.yml
build.gradle
gradle/root/publishing.gradle

- Get 3rd party dependencies from nexus
- Don't test against JDK 14

Get 3rd party dependencies from nexus

---

docs/userguide/src/site/pages/thredds/NcssRef.md
tds/src/main/webapp/WEB-INF/templates/ncssFragments.html

Remove hardcoded versions from documentation links

Minor documentation improvements

---

dap4/d4servlet/build.gradle

Make dependency implementation so it is available at runtime for the d4ts war as well as the tds war

Fix dependency scope

---

.github/workflows/docs.yml
.github/workflows/tds.yml

Update upload-artifacts version in github actions

Update github actions

---

tds/src/main/java/thredds/server/radarServer2/RadarDataInventory.java

Fix potential nullptr exception in RadarServer code

Fix nullptr exception

---

docs/adminguide/src/site/pages/thredds/WmsConfig.md
docs/quickstart/src/site/pages/tds_tutorial/production/Upgrade.md
docs/userguide/src/site/pages/tds_tutorial/production/Upgrade.md
docs/userguide/src/site/pages/thredds/WmsConfig.md
tds/src/main/java/thredds/server/wms/TdsEnhancedVariableMetadata.java
tds/src/main/java/thredds/server/wms/config/LayerSettings.java
tds/src/main/java/thredds/server/wms/config/WmsDetailedConfig.java
tds/src/main/resources/schema/wmsConfig.dtd
tds/src/main/resources/schema/wmsConfig_2_0.dtd
tds/src/main/webapp/WEB-INF/altContent/startup/wmsConfig.xml
tds/src/test/content/thredds/wmsConfig.xml
tds/src/test/java/thredds/server/wms/config/WmsDetailedConfigTest.java

Support the following new default config options in wmsConfig:
* defaultAboveMaxColor
* defaultBelowMinColor
* defaultNoDataColor
* defaultOpacity

wmsConfig enhancements

---

docs/adminguide/src/site/pages/thredds/WmsRef.md
docs/quickstart/src/site/pages/thredds/WmsRef.md
docs/userguide/src/site/pages/thredds/WmsRef.md
tds/src/integrationTests/java/thredds/server/wms/TestGodiva3.java
tds/src/main/java/thredds/server/config/TdsContext.java
tds/src/main/webapp/WEB-INF/web.xml
tds/src/test/content/thredds/godiva3.properties

Allow for godiva3 configuration using godiva3.properties.
Fixes Unidata/tds#469

Support godiva3 configuration

---

docs/build.gradle
project-files/jenkins/pipelines/docs

Update docker image used to build docs from v0.0.4 to v0.0.5.

Update docker image used to build docs

---

.github/workflows/tds.yml

* update github actions to use thredds-test-action v3, which is based on
* ubuntu 24.04 (v2 based on 20.04) add corretto to test matrix on github actions

Update to thredds-test-action v3

---

gradle/any/shared-mvn-coords.gradle
tds-platform/build.gradle

Upgrade to netCDF-Java 5.8.0-SNAPSHOT
Upgrade to spring-security 6.4.4

Dependency upgrades

---

gradle/any/shared-mvn-coords.gradle
tds-platform/build.gradle

Upgrade the following dependencies:
* netCDF-Java (5.8.0-SNAPSHOT -> 5.8.0 release)
* Spring Security (6.4.4 -> 6.4.5)

Upgrade dependencies
